# -*- coding: utf-8 -*-
"""Copy of Firefightersreal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OU-y_58IqfaE31EvQYHLlgy4rr1nJO56
"""

#

#!pip install numpy scipy matplotlib seaborn scikit-learn mesa -q

from mesa import Agent, Model
from mesa.space import MultiGrid
from mesa.datacollection import DataCollector
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import matplotlib.patches as patches
from matplotlib.lines import Line2D
import numpy as np
import pandas as pd
import copy
from collections import deque

from mesa import Agent
from collections import deque
import numpy as np

class Bombero(Agent):
    def __init__(self, model, energia_maxima=4):
        super().__init__(model)

        self.visited = 0
        self.apagarFuego = 0
        self.apagarHumo = 0
        self.civilesRes = 0
        self.puertas_abiertas = 0
        self.energia_maxima = energia_maxima
        self.energia_actual = energia_maxima
        self.energia_guardada = 0
        self.tieneCivil = False
        self.celdas_exploradas = set()
        self.ultimo_objetivo = None
        self.herido = False  # NUEVO: indica si el bombero está herido

    def puede_moverse(self, desde, hacia):
        if not self.model.hay_pared_entre(desde, hacia):
            return True
        if self.model.hay_puerta_entre(desde, hacia):
            return self.model.esta_puerta_abierta(desde, hacia)
        return False

    def abrir_puerta(self, desde, hacia):
        if self.energia_actual < 1:
            return False
        if self.model.hay_puerta_entre(desde, hacia):
            if not self.model.esta_puerta_abierta(desde, hacia):
                key = tuple(sorted([desde, hacia]))
                self.model.puertas[key]['abierta'] = True
                self.energia_actual -= 1
                self.puertas_abiertas += 1
                return True
        return False

    def apagar_fuego(self):
        """Apaga el fuego en la celda actual (cuesta 1 energía)"""
        if self.energia_actual < 1:
            return False
        if self.model.tieneFuegoEn(self.pos):
            self.model.quitarFuego(self.pos)
            self.energia_actual -= 1
            self.apagarFuego += 1
            return True
        return False

    def apagar_humo(self):
        """Apaga el humo en la celda actual (cuesta 1 energía)"""
        if self.energia_actual < 1:
            return False
        if self.model.tieneHumoEn(self.pos):
            self.model.quitarHumo(self.pos)
            self.energia_actual -= 1
            self.apagarHumo += 1
            return True
        return False

    def gastar_energia(self, cantidad=1):
        if self.energia_actual >= cantidad:
            self.energia_actual -= cantidad
            return True
        return False

    def get_neighbors(self):
        return self.model.grid.get_neighborhood(
            self.pos, moore=False, include_center=False
        )

    def buscar_camino_bfs(self, objetivo):
        if self.pos == objetivo:
            return []
        visitados = {self.pos}
        cola = deque([(self.pos, [])])

        while cola:
            actual, camino = cola.popleft()
            vecinos = self.model.grid.get_neighborhood(
                actual, moore=False, include_center=False
            )
            for vecino in vecinos:
                if vecino not in visitados:
                    puede_pasar = self.puede_moverse(actual, vecino)
                    hay_puerta = self.model.hay_puerta_entre(actual, vecino)
                    if puede_pasar:
                        nuevo_camino = camino + [vecino]
                        if vecino == objetivo:
                            return nuevo_camino
                        visitados.add(vecino)
                        cola.append((vecino, nuevo_camino))
        return None

    def encontrar_poi_mas_cercano(self):
        """Encuentra el POI (punto de interés) más cercano"""
        pois = []
        for pos in self.model.posicionesPOI:
            camino = self.buscar_camino_bfs(pos)
            if camino is not None:
                pois.append((pos, len(camino)))
        if not pois:
            return None
        poi_cercano = min(pois, key=lambda x: x[1])
        return poi_cercano[0]

    def base_mas_cercana(self):
        """Devuelve la base más cercana al bombero usando BFS real."""
        bases_con_distancia = []

        for base in self.model.base_position:  # lista de posiciones
            camino = self.buscar_camino_bfs(base)
            if camino is not None:
                bases_con_distancia.append((base, len(camino)))

        if not bases_con_distancia:
            return None  # No hay camino a ninguna base

        # Base con menor distancia
        return min(bases_con_distancia, key=lambda x: x[1])[0]

    def respawnear_en_base(self):
        """
        Cuando el bombero recibe daño, desaparece de su posición actual
        y reaparece en la base más cercana.
        Si llevaba un civil, el civil se pierde.
        """
        # Si llevaba un civil, se pierde
        if self.tieneCivil:
            self.tieneCivil = False
            self.model.civiles_perdidos += 1

        # Encontrar la base más cercana

        base_destino = self.base_mas_cercana()

        if base_destino is None:
            # Si no encuentra camino, usar la primera base disponible
            base_destino = self.model.base_position[0]

        # Mover al bombero a la base
        self.model.grid.move_agent(self, base_destino)

        # Resetear estado del bombero
        self.herido = False
        self.energia_actual = 0  # Pierde toda la energía del turno
        self.energia_guardada = 0



    def encontrar_civil_revelado_mas_cercano(self):
        """Encuentra el civil ya revelado más cercano"""
        civiles = []
        for pos, revelado in self.model.civiles_revelados.items():
            if revelado:  # Solo civiles revelados
                camino = self.buscar_camino_bfs(pos)
                if camino is not None:
                    civiles.append((pos, len(camino)))
        if not civiles:
            return None
        return min(civiles, key=lambda x: x[1])[0]

    def encontrar_fuego_mas_cercano(self):
        """Encuentra el fuego más cercano"""
        fuegos = []
        for pos in self.model.posicionesFuego:
            camino = self.buscar_camino_bfs(pos)
            if camino is not None:
                fuegos.append((pos, len(camino)))
        if not fuegos:
            return None
        return min(fuegos, key=lambda x: x[1])[0]

    def mover_hacia(self, objetivo):
        if self.energia_actual < 1:
            return False
        camino = self.buscar_camino_bfs(objetivo)
        if not camino:
            return False
        siguiente = camino[0]

        if self.puede_moverse(self.pos, siguiente):
            self.model.grid.move_agent(self, siguiente)
            self.visited += 1
            self.energia_actual -= 1
            self.celdas_exploradas.add(siguiente)

            # Verificar si llegó a un POI
            if self.model.is_poi(siguiente):
                tipo = self.model.revelar_poi(siguiente)
                if tipo == 'civil':
                    # Recoger civil
                    self.model.quitar_civil(siguiente)
                    self.civilesRes += 1
                    self.tieneCivil = True
                    # CORRECCIÓN: usar "in" en lugar de "=="
                    if siguiente in self.model.base_position:
                        self.tieneCivil = False
                        self.model.civiles_rescatados += 1  # AÑADIR: incrementar contador
                # Si es falsa alarma, no hace nada (ya se removió del tablero)

            # AÑADIR: Verificar si llegó a base con civil
            if self.tieneCivil and siguiente in self.model.base_position:
                self.tieneCivil = False
                self.model.civiles_rescatados += 1

            return True

        elif self.model.hay_puerta_entre(self.pos, siguiente):
            if not self.model.esta_puerta_abierta(self.pos, siguiente):
                return self.abrir_puerta(self.pos, siguiente)
        return False

    def movimiento_aleatorio(self):
        if self.energia_actual < 1:
            return False
        vecinos = list(self.get_neighbors())
        if not vecinos:
            return self.gastar_energia()
        np.random.shuffle(vecinos)

        for vecino in vecinos:
            if self.puede_moverse(self.pos, vecino):
                self.model.grid.move_agent(self, vecino)
                self.visited += 1
                self.energia_actual -= 1

                # Verificar si llegó a un POI
                if self.model.is_poi(vecino):
                    tipo = self.model.revelar_poi(vecino)
                    if tipo == 'civil':
                        self.model.quitar_civil(vecino)
                        self.civilesRes += 1
                        self.tieneCivil = True
                        # CORRECCIÓN: usar "in" en lugar de "=="
                        if vecino in self.model.base_position:
                            self.tieneCivil = False
                            self.model.civiles_rescatados += 1  # AÑADIR

                # AÑADIR: Verificar si llegó a base con civil
                if self.tieneCivil and vecino in self.model.base_position:
                    self.tieneCivil = False
                    self.model.civiles_rescatados += 1

                return True

        for vecino in vecinos:
            if self.model.hay_puerta_entre(self.pos, vecino):
                if not self.model.esta_puerta_abierta(self.pos, vecino):
                    return self.abrir_puerta(self.pos, vecino)

        return self.gastar_energia()


    def step(self):
        self.energia_actual = self.energia_maxima + self.energia_guardada
        self.energia_guardada = 0
        self.celdas_exploradas.add(self.pos)

        # CORRECCIÓN: usar "in" para verificar si está en alguna base
        if self.pos in self.model.base_position and self.tieneCivil:
            self.tieneCivil = False
            self.model.civiles_rescatados += 1  # AÑADIR: incrementar contador

        while self.energia_actual > 0:
            accion_realizada = False

            # PRIORIDAD 1: Apagar fuego en posición actual
            if self.model.tieneFuegoEn(self.pos):
                accion_realizada = self.apagar_fuego()
                if accion_realizada:
                    continue

            # PRIORIDAD 2: Apagar humo en posición actual
            if self.model.tieneHumoEn(self.pos):
                accion_realizada = self.apagar_humo()
                if accion_realizada:
                    continue

            # PRIORIDAD 3: Si tiene civil, ir a la base MÁS CERCANA
            if self.tieneCivil:
                # CORRECCIÓN: Verificar con "in" si ya está en una base
                if self.pos not in self.model.base_position:
                    # Encontrar la base más cercana
                    bases_con_distancia = []
                    for base in self.model.base_position:
                        camino = self.buscar_camino_bfs(base)
                        if camino is not None:
                            bases_con_distancia.append((base, len(camino)))

                    if bases_con_distancia:
                        base_mas_cercana = min(bases_con_distancia, key=lambda x: x[1])[0]
                        accion_realizada = self.mover_hacia(base_mas_cercana)
                    else:
                        accion_realizada = self.gastar_energia()
                else:
                    # Ya está en base, entregar civil (esto ya debería haberse hecho arriba)
                    if self.tieneCivil:
                        self.tieneCivil = False
                        self.model.civiles_rescatados += 1
                    accion_realizada = True  # Marcar como acción realizada

            else:
                # PRIORIDAD 4: Buscar civil revelado
                civil_objetivo = self.encontrar_civil_revelado_mas_cercano()
                if civil_objetivo:
                    accion_realizada = self.mover_hacia(civil_objetivo)
                else:
                    # PRIORIDAD 5: Buscar POI no revelado
                    poi_objetivo = self.encontrar_poi_mas_cercano()
                    if poi_objetivo:
                        accion_realizada = self.mover_hacia(poi_objetivo)
                    else:
                        # PRIORIDAD 6: Combatir fuego
                        fuego_objetivo = self.encontrar_fuego_mas_cercano()
                        if fuego_objetivo:
                            accion_realizada = self.mover_hacia(fuego_objetivo)
                        else:
                            accion_realizada = self.movimiento_aleatorio()

            if not accion_realizada:
                self.gastar_energia()

        if self.energia_actual > 0:
            self.energia_guardada = min(self.energia_actual, self.energia_maxima)

    def step_micro(self):
        """
        Versión 'micro' del step:
        - Si empieza turno, recarga energía.
        - Hace SOLO UNA acción con la misma prioridad que step().
        - Baja la energía acorde a la acción.
        """

        # Si no tiene energía, empieza turno nuevo
        if self.energia_actual <= 0:
            self.energia_actual = self.energia_maxima + self.energia_guardada
            self.energia_guardada = 0
            self.celdas_exploradas.add(self.pos)

            # Entregar civil si está en base al comenzar el turno
            if self.pos in self.model.base_position and self.tieneCivil:
                self.tieneCivil = False
                self.model.civiles_rescatados += 1

        # Si aún así no tiene energía, no hace nada
        if self.energia_actual <= 0:
            return

        accion_realizada = False

        # PRIORIDAD 1: Apagar fuego en posición actual
        if self.model.tieneFuegoEn(self.pos):
            accion_realizada = self.apagar_fuego()

        # PRIORIDAD 2: Apagar humo en posición actual
        if not accion_realizada and self.model.tieneHumoEn(self.pos):
            accion_realizada = self.apagar_humo()

        # PRIORIDAD 3: Si tiene civil, ir a la base MÁS CERCANA
        if not accion_realizada and self.tieneCivil:
            if self.pos not in self.model.base_position:
                bases_con_distancia = []
                for base in self.model.base_position:
                    camino = self.buscar_camino_bfs(base)
                    if camino is not None:
                        bases_con_distancia.append((base, len(camino)))

                if bases_con_distancia:
                    base_mas_cercana = min(bases_con_distancia, key=lambda x: x[1])[0]
                    accion_realizada = self.mover_hacia(base_mas_cercana)
                else:
                    accion_realizada = self.gastar_energia()
            else:
                # Ya está en base: entregar civil (por si llegó justo en el micro anterior)
                if self.tieneCivil:
                    self.tieneCivil = False
                    self.model.civiles_rescatados += 1
                accion_realizada = True

        # PRIORIDAD 4–6: si NO tiene civil
        if not accion_realizada and not self.tieneCivil:
            # PRIORIDAD 4: Buscar civil revelado
            civil_objetivo = self.encontrar_civil_revelado_mas_cercano()
            if civil_objetivo:
                accion_realizada = self.mover_hacia(civil_objetivo)
            else:
                # PRIORIDAD 5: Buscar POI no revelado
                poi_objetivo = self.encontrar_poi_mas_cercano()
                if poi_objetivo:
                    accion_realizada = self.mover_hacia(poi_objetivo)
                else:
                    # PRIORIDAD 6: Combatir fuego
                    fuego_objetivo = self.encontrar_fuego_mas_cercano()
                    if fuego_objetivo:
                        accion_realizada = self.mover_hacia(fuego_objetivo)
                    else:
                        # Sin objetivos: moverse aleatorio
                        accion_realizada = self.movimiento_aleatorio()

        # Si ninguna acción cambió nada, gastar energía
        if not accion_realizada:
            self.gastar_energia()

        # (Opcional) Si quisieras usar energía guardada aquí, podrías tocar self.energia_guardada,
        # pero en tu lógica original casi siempre termina en 0 al final del turno, así que lo dejamos igual.



class BomberoAleatorio(Bombero):
    def step(self):
        self.energia_actual = self.energia_maxima + self.energia_guardada
        self.energia_guardada = 0

        # Entregar civil en base
        if self.pos in self.model.base_position and self.tieneCivil:
            self.tieneCivil = False
            self.model.civiles_rescatados += 1

        # Si está herido, regresar a base
        if self.herido:
            if self.pos in self.model.base_position:
                self.herido = False
                return
            else:
                base = self.base_mas_cercana()
                if base is not None:
                    while self.energia_actual > 0:
                        if not self.mover_hacia(base):
                            self.gastar_energia()
                        if self.pos in self.model.base_position:
                            break
                return

        while self.energia_actual > 0:
            # Usar np.random para probabilidades
            accion = np.random.choice(['mover', 'puerta', 'fuego', 'humo', 'nada'],
                                     p=[0.5, 0.15, 0.15, 0.1, 0.1])

            if accion == 'mover':
                self.movimiento_aleatorio()
            elif accion == 'puerta':
                vecinos = list(self.get_neighbors())
                if vecinos:
                    vecino = vecinos[np.random.randint(len(vecinos))]
                    if self.model.hay_puerta_entre(self.pos, vecino):
                        self.abrir_puerta(self.pos, vecino)
                    else:
                        self.gastar_energia()
                else:
                    self.gastar_energia()
            elif accion == 'fuego':
                if not self.apagar_fuego():
                    self.gastar_energia()
            elif accion == 'humo':
                if not self.apagar_humo():
                    self.gastar_energia()
            else:
                self.gastar_energia()

        if self.energia_actual > 0:
            self.energia_guardada = min(self.energia_actual, self.energia_maxima)

from mesa import Model
from mesa.space import MultiGrid

import numpy as np

class Tablero(Model):
    def __init__(self, width=8, height=6, num_agentes=6, tipo_agente=None, archivo_config=None):
        super().__init__()

        self.grid = MultiGrid(width, height, torus=False)
        self.schedule = []
        self.current_id = 0
        self.base_position = [(0,2), (5,0), (7,3),(2,5)]  # 4 bases
        self.cells = np.zeros((width, height))  # Ya no usaremos esto para civiles
        self.paredes = {}
        self.puertas = {}
        self.paredes_dano = {}  # Nuevo: daño en paredes
        self.steps = 0
        self.civiles_rescatados = 0
        self.civiles_perdidos = 0
        self.puntos_dano = 0
        self.tipo_agente = tipo_agente
        self.explosiones_generadas = 0


        self.done = False      # Ya terminó la simulación?
        self.outcome = None    # "win" o "lose"
        self.end_reason = "" # Texto: "4 civiles heridos", "Edificio colapsado", etc.
        self.end_code = ""

        # Sistema de POI (Puntos de Interés)
        self.posicionesPOI = set()  # POI visibles en el tablero (siempre 3)
        self.poi_sin_revelar = []   # Lista de (pos, tipo) donde tipo='v' o 'f'
        self.civiles_revelados = {}  # {pos: True} - civiles que ya fueron revelados
        self.falsas_alarmas_reveladas = set()  # posiciones de falsas alarmas reveladas

        # Estados del fuego/humo/daño
        self.posicionesFuego = set()
        self.posicionesHumo = set()
        self.posicionesDano = set()

        self.datacollector = DataCollector(
            model_reporters={
                "Civiles_rescatados": lambda m: m.civiles_rescatados,
                "Civiles_perdidos": lambda m: m.civiles_perdidos,
                "POI_activos": lambda m: len(m.posicionesPOI),
                "Puertas_abiertas": lambda m: sum(1 for p in m.puertas.values() if p.get('abierta')),
                "Steps": lambda m: m.steps,
                "Fuegos_Activos": lambda m: len(m.posicionesFuego),
                "Humo_Activos": lambda m: len(m.posicionesHumo),
                "Puntos_Dano": lambda m: m.puntos_dano,
                "Explosiones_generadas": lambda m: m.explosiones_generadas
            },
            agent_reporters={
                "Civiles": lambda a: a.civilesRes,
                "Visitadas": lambda a: a.visited,
                "Fuegos_Apagados": lambda a: a.apagarFuego,
            }
        )

        if archivo_config:
            self.cargar_configuracion(archivo_config)
        else:
            self.configuracion_default()

        # Colocar 3 POI iniciales
        self.colocar_poi_iniciales()

        for i in range(num_agentes):
            self.agregar_bombero()

        self.datacollector.collect(self)

    def agregar_bombero(self):
        """Agrega un bombero en posición válida"""
        intentos = 0
        max_intentos = 100

        while intentos < max_intentos:
            x = self.random.randrange(self.grid.width)
            y = self.random.randrange(self.grid.height)

            if (self.grid.is_cell_empty((x, y)) and
                (x, y) not in self.base_position and
                (x, y) not in self.posicionesPOI and
                (x, y) not in self.posicionesFuego):

                try:
                    #bombero = self.tipo_agente(self)
                    bombero = Bombero(self)
                    self.grid.place_agent(bombero, (x, y))
                    self.schedule.append(bombero)
                    return True
                except Exception as e:
                    print(f"Error al agregar bombero en ({x},{y}): {e}")
                    pass

            intentos += 1

        print(f"Advertencia: No se pudo colocar bombero después de {max_intentos} intentos")
        return False

    def cargar_configuracion(self, archivo):
        with open(archivo, 'r') as f:
            lines = [line.strip() for line in f.readlines() if line.strip()]

        idx = 0

        # 1. Cargar paredes (6 líneas)
        for row in range(6):
            if idx >= len(lines):
                break
            line_parts = lines[idx].split()
            for col in range(min(8, len(line_parts))):
                wall_config = line_parts[col]
                if len(wall_config) == 4:
                    self.paredes[(col, row)] = {
                        'arriba': wall_config[0] == '1',
                        'derecha': wall_config[1] == '1',
                        'abajo': wall_config[2] == '1',
                        'izquierda': wall_config[3] == '1'
                    }
                    # Inicializar daño en paredes
                    self.paredes_dano[(col, row)] = {
                        'arriba': 0, 'izquierda': 0, 'abajo': 0, 'derecha': 0
                    }
            idx += 1

        # 2. Cargar POI (3 líneas iniciales, pero crearemos pool de 15)
        poi_iniciales = []
        for _ in range(3):
            if idx >= len(lines):
                break
            parts = lines[idx].split()
            if len(parts) >= 3:
                row = int(parts[0]) - 1
                col = int(parts[1]) - 1
                tipo = parts[2]  # 'v' o 'f'
                if 0 <= row < 6 and 0 <= col < 8:
                    poi_iniciales.append(((col, row), tipo))
            idx += 1

        # Crear pool de 15 POI (10 civiles, 5 falsas alarmas)
        # Los primeros 3 del archivo + 12 aleatorios
        self.poi_sin_revelar = poi_iniciales.copy()

        # Generar 12 POI adicionales aleatorios
        civiles_necesarios = 10 - sum(1 for _, tipo in poi_iniciales if tipo == 'v')
        falsas_necesarias = 5 - sum(1 for _, tipo in poi_iniciales if tipo == 'f')

        posiciones_ocupadas = {pos for pos, _ in poi_iniciales}
        # Agregar todas las bases a posiciones ocupadas
        for base_pos in self.base_position:
            posiciones_ocupadas.add(base_pos)

        # Generar civiles
        for _ in range(civiles_necesarios):
            while True:
                x = self.random.randrange(self.grid.width)
                y = self.random.randrange(self.grid.height)
                if (x, y) not in posiciones_ocupadas and (x, y) not in self.base_position:
                    self.poi_sin_revelar.append(((x, y), 'v'))
                    posiciones_ocupadas.add((x, y))
                    break

        # Generar falsas alarmas
        for _ in range(falsas_necesarias):
            while True:
                x = self.random.randrange(self.grid.width)
                y = self.random.randrange(self.grid.height)
                if (x, y) not in posiciones_ocupadas and (x, y) not in self.base_position:
                    self.poi_sin_revelar.append(((x, y), 'f'))
                    posiciones_ocupadas.add((x, y))
                    break

        # Mezclar el pool
        self.random.shuffle(self.poi_sin_revelar)

        # 3. Cargar posiciones iniciales de fuego (10 líneas)
        for _ in range(10):
            if idx >= len(lines):
                break
            parts = lines[idx].split()
            if len(parts) >= 2:
                row = int(parts[0]) - 1
                col = int(parts[1]) - 1
                if 0 <= row < 6 and 0 <= col < 8:
                    self.posicionesFuego.add((col, row))
            idx += 1

        # 4. Cargar puertas (8 líneas)
        for _ in range(8):
            if idx >= len(lines):
                break
            parts = lines[idx].split()
            if len(parts) >= 4:
                r1 = int(parts[0]) - 1
                c1 = int(parts[1]) - 1
                r2 = int(parts[2]) - 1
                c2 = int(parts[3]) - 1
                if (0 <= r1 < 6 and 0 <= c1 < 8 and 0 <= r2 < 6 and 0 <= c2 < 8):
                    celda1 = (c1, r1)
                    celda2 = (c2, r2)
                    key = tuple(sorted([celda1, celda2]))
                    self.puertas[key] = {'abierta': False}
            idx += 1

    def colocar_poi_iniciales(self):
        """Coloca 3 POI en el tablero desde el pool"""
        for _ in range(min(3, len(self.poi_sin_revelar))):
            if self.poi_sin_revelar:
                pos, tipo = self.poi_sin_revelar.pop(0)
                # Si hay fuego en esa posición, no colocar ahí
                if pos not in self.posicionesFuego:
                    self.posicionesPOI.add(pos)
                    # Guardar el tipo para cuando se revele
                    if tipo == 'v':
                        self.civiles_revelados[pos] = False  # No revelado aún
                    # Las falsas alarmas no necesitan tracking especial

    def generar_nuevo_poi(self):
        """Genera un nuevo POI en posición válida"""
        if not self.poi_sin_revelar:
            return  # No hay más POI disponibles

        intentos = 0
        while intentos < 50 and self.poi_sin_revelar:
            pos, tipo = self.poi_sin_revelar.pop(0)

            # Verificar que no haya fuego
            if pos not in self.posicionesFuego and pos not in self.posicionesPOI:
                self.posicionesPOI.add(pos)
                if tipo == 'v':
                    self.civiles_revelados[pos] = False
                return
            else:
                # Si había fuego, generar otro
                intentos += 1

        # Si no pudimos colocar, poner en posición aleatoria válida
        if self.poi_sin_revelar:
            pos, tipo = self.poi_sin_revelar.pop(0)
            intentos = 0
            while intentos < 100:
                x = self.random.randrange(self.grid.width)
                y = self.random.randrange(self.grid.height)
                if ((x, y) not in self.posicionesFuego and
                    (x, y) not in self.posicionesPOI and
                    (x, y) not in self.base_position):
                    self.posicionesPOI.add((x, y))
                    if tipo == 'v':
                        self.civiles_revelados[(x, y)] = False
                    return
                intentos += 1

    def configuracion_default(self):
        for x in range(self.grid.width):
            for y in range(self.grid.height):
                self.paredes[(x, y)] = {
                    'arriba': y == 0,
                    'abajo': y == self.grid.height - 1,
                    'izquierda': x == 0,
                    'derecha': x == self.grid.width - 1
                }
                self.paredes_dano[(x, y)] = {
                    'arriba': 0, 'izquierda': 0, 'abajo': 0, 'derecha': 0
                }

    def hay_pared_entre(self, celda1, celda2):
        """Verifica si hay pared entre dos celdas (considerando daño)"""
        x1, y1 = celda1
        x2, y2 = celda2

        if abs(x1 - x2) + abs(y1 - y2) != 1:
            return False

        direccion = None
        if x2 > x1:
            direccion = 'derecha'
        elif x2 < x1:
            direccion = 'izquierda'
        elif y2 > y1:
            direccion = 'abajo'
        elif y2 < y1:
            direccion = 'arriba'

        # Si la pared tiene 2+ de daño, está destruida
        if self.paredes_dano.get(celda1, {}).get(direccion, 0) >= 2:
            return False

        return self.paredes.get(celda1, {}).get(direccion, False)

    def hay_puerta_entre(self, celda1, celda2):
        key = tuple(sorted([celda1, celda2]))
        return key in self.puertas

    def esta_puerta_abierta(self, celda1, celda2):
        key = tuple(sorted([celda1, celda2]))
        return self.puertas.get(key, {}).get('abierta', False)

    def is_poi(self, pos):
        """Verifica si hay un POI en esta posición"""
        return pos in self.posicionesPOI

    def revelar_poi(self, pos):
        """Revela un POI: puede ser civil o falsa alarma"""
        if pos not in self.posicionesPOI:
            return None

        # Determinar si es civil o falsa alarma
        if pos in self.civiles_revelados:
            # Es un civil
            self.civiles_revelados[pos] = True  # Marcar como revelado
            return 'civil'
        else:
            # Es falsa alarma
            self.falsas_alarmas_reveladas.add(pos)
            self.posicionesPOI.remove(pos)
            # Generar nuevo POI
            if len(self.posicionesPOI) < 3:
                self.generar_nuevo_poi()
            return 'falsa_alarma'

    def quitar_civil(self, pos):
        """Rescata un civil (solo si está revelado)"""
        if pos in self.civiles_revelados and self.civiles_revelados[pos]:
            del self.civiles_revelados[pos]
            self.posicionesPOI.discard(pos)
            # Generar nuevo POI
            if len(self.posicionesPOI) < 3:
                self.generar_nuevo_poi()
            return True
        return False

    def is_all_collected(self):
        """Victoria: 7 civiles rescatados"""
        return self.civiles_rescatados >= 7

    def all_agents_empty(self):
        return all(not a.tieneCivil for a in self.schedule)

    def verificar_game_over(self):
        """Verifica condiciones de derrota"""
        if self.civiles_perdidos >= 4:
            return True, "4 civiles heridos"
        if self.puntos_dano >= 25:
            return True, "Edificio colapsado"
        return False, None

    def entregar_civil_en_base(self):
      """Cuenta un civil como realmente rescatado al llegar a la base."""
      self.civiles_rescatados += 1

    # ========== MÉTODOS DE FUEGO ==========

    def tieneFuegoEn(self, pos):
        return pos in self.posicionesFuego

    def tieneHumoEn(self, pos):
        return pos in self.posicionesHumo

    def tieneDanoEn(self, pos):
        return pos in self.posicionesDano

    def obtenerPosicionesFuego(self):
        return list(self.posicionesFuego)

    def esPosicionValida(self, pos):
        x, y = pos
        return 0 <= x < self.grid.width and 0 <= y < self.grid.height

    def puedePropagar(self, origen, destino):
        """Determina si el fuego/humo puede propagarse entre dos celdas"""
        x1, y1 = origen
        x2, y2 = destino

        if not (0 <= x2 < self.grid.width and 0 <= y2 < self.grid.height):
            return False

        if x2 == x1 and y2 == y1 - 1:
            dir_origen, dir_destino = 'arriba', 'abajo'
        elif x2 == x1 and y2 == y1 + 1:
            dir_origen, dir_destino = 'abajo', 'arriba'
        elif y2 == y1 and x2 == x1 - 1:
            dir_origen, dir_destino = 'izquierda', 'derecha'
        elif y2 == y1 and x2 == x1 + 1:
            dir_origen, dir_destino = 'derecha', 'izquierda'
        else:
            return False

        # Si pared tiene 2+ daño, está destruida
        if self.paredes_dano[(x1, y1)].get(dir_origen, 0) >= 2:
            return True

        # Si hay pared intacta, no se propaga
        if self.paredes[(x1, y1)].get(dir_origen, False):
            return False
        if self.paredes[(x2, y2)].get(dir_destino, False):
            return False

        # Si hay puerta
        clave = tuple(sorted([origen, destino]))
        if clave in self.puertas:
            return self.puertas[clave]['abierta']

        return True

    def propagarFuego(self):
        """Propaga fuego con probabilidad del 10%.
        Además: si hay HUMO adyacente a un fuego, el HUMO se convierte en FUEGO inmediatamente.
        """
        nuevosFuegos = set()

        for posFuego in list(self.posicionesFuego):
            x, y = posFuego
            adyacentes = [(x-1,y), (x+1,y), (x,y-1), (x,y+1)]

            for adjPos in adyacentes:
                if not self.esPosicionValida(adjPos):
                    continue

                # Si hay HUMO al lado del fuego → se convierte en fuego inmediatamente
                if adjPos in self.posicionesHumo and self.puedePropagar(posFuego, adjPos):
                    self.posicionesHumo.discard(adjPos)
                    nuevosFuegos.add(adjPos)
                    continue

                # Propagación normal con probabilidad 10% a celdas sin fuego
                if (self.puedePropagar(posFuego, adjPos) and
                    not self.tieneFuegoEn(adjPos) and
                    self.random.random() < 0.10):
                    nuevosFuegos.add(adjPos)

        self.posicionesFuego.update(nuevosFuegos)

        # Verificar si fuego revela/hiere POIs
        for pos in nuevosFuegos:
            if pos in self.posicionesPOI:
                if pos in self.civiles_revelados:
                    # Civil herido
                    self.civiles_perdidos += 1
                    del self.civiles_revelados[pos]
                    self.posicionesPOI.remove(pos)
                    if len(self.posicionesPOI) < 3:
                        self.generar_nuevo_poi()
                else:
                    # Falsa alarma quemada
                    self.posicionesPOI.remove(pos)
                    if len(self.posicionesPOI) < 3:
                        self.generar_nuevo_poi()

    def quitarFuego(self, pos):
        if pos in self.posicionesFuego:
            self.posicionesFuego.remove(pos)

    def generar_humo_aleatorio(self):
        """
        Genera HUMO de forma ALEATORIA en UNA celda por turno
        Reglas:
        - vacío/bombero → humo
        - humo → fuego (revela POI si aplica, daña bomberos)
        - fuego → explosión

        MODIFICADO: Si hay bombero, respawnea en base en lugar de quedar herido
        """
        # Seleccionar UNA celda aleatoria del tablero
        x = self.random.randrange(self.grid.width)
        y = self.random.randrange(self.grid.height)
        pos = (x, y)

        # Aplicar reglas de propagación
        if pos in self.posicionesFuego:
            # Si hay fuego → EXPLOSIÓN
            self.explosion(pos)

        elif pos in self.posicionesHumo:
            # Si hay humo → se convierte en FUEGO
            self.posicionesHumo.discard(pos)
            self.posicionesFuego.add(pos)

            # Verificar si hay bomberos en esta posición
            agents_in_cell = self.grid.get_cell_list_contents([pos])
            for agent in agents_in_cell:
                # Verificar si es un bombero (cualquier subclase)
                if hasattr(agent, 'herido'):
                    # MODIFICADO: En lugar de marcar como herido, respawnear en base
                    agent.respawnear_en_base()

            # Si el fuego revela un POI
            if pos in self.posicionesPOI:
                if pos in self.civiles_revelados:
                    # Civil herido
                    self.civiles_perdidos += 1
                    del self.civiles_revelados[pos]
                    self.posicionesPOI.remove(pos)
                    if len(self.posicionesPOI) < 3:
                        self.generar_nuevo_poi()
                else:
                    # Falsa alarma quemada
                    self.posicionesPOI.remove(pos)
                    if len(self.posicionesPOI) < 3:
                        self.generar_nuevo_poi()
        else:
            # Si está vacío (puede haber bombero) → generar HUMO
            self.posicionesHumo.add(pos)

    def generarHumo(self):
        """
        Ya no genera humo automáticamente.
        El humo se genera por la propagación aleatoria de fuego.
        """
        pass  # Deshabilitado - el humo se genera en propagarFuego()

    def quitarHumo(self, pos):
        if pos in self.posicionesHumo:
            self.posicionesHumo.remove(pos)

    def verificarExplosiones(self):
        """Si una celda tiene >= 4 celdas de fuego adyacentes, explota"""
        for pos in list(self.posicionesFuego):
            x, y = pos
            fuegosAdyacentes = 0
            adyacentes = [(x-1,y), (x+1,y), (x,y-1), (x,y+1)]

            for adjPos in adyacentes:
                if self.tieneFuegoEn(adjPos):
                    fuegosAdyacentes += 1

            if fuegosAdyacentes >= 4:
                self.explosion(pos)


    def explosion(self, pos):
        """Causa daño y elimina el fuego en la celda.
        Reglas nuevas:
        - Genera fuego en los 4 lados cardinales.
        - Si en la dirección inmediata hay fuego, 'salta' al siguiente bloque (repite hasta chocar con pared/puerta o casilla sin fuego).
        - Si se encuentra HUMO en el camino, lo convierte en FUEGO.
        - Si choca con una PARED (o con el límite), causa 1 de daño; si es PUERTA, se abre y sufre 2 de daño.
        """
        x0, y0 = pos

        # Marcar daño local y eliminar fuego de la celda explotada
        self.puntos_dano += 2
        self.explosiones_generadas += 1
        self.posicionesDano.add(pos)
        self.posicionesFuego.discard(pos)

        # Lados cardinales
        direcciones = {
            'derecha': (1, 0),
            'izquierda': (-1, 0),
            'abajo': (0, 1),
            'arriba': (0, -1)
        }

        for lado, (dx, dy) in direcciones.items():
            cx, cy = x0 + dx, y0 + dy  # comienzo en la celda adyacente
            ultimo_valido = (x0, y0)  # por defecto la celda explotada

            # seguir avanzando mientras la casilla tenga fuego (salta)
            while True:
                siguiente = (cx, cy)

                # Si fuera de tablero → choca con pared exterior del último válido
                if not self.esPosicionValida(siguiente):
                    # aplicar daño a la pared exterior del ultimo_valido
                    # cantidad 1 para pared exterior, 2 si puerta (no hay puerta fuera de tablero)
                    # determinamos el 'pos2' fuera de tablero para calcular lado
                    self.danar_pared_entre(ultimo_valido, siguiente, amount=1)
                    break

                # Si hay pared entre ultimo_valido y siguiente que bloquea la propagación:
                if not self.puedePropagar(ultimo_valido, siguiente):
                    # Si hay una puerta entre ultimo_valido y siguiente, la danamos/abrimos:
                    # detectar si existe puerta entre ultimo_valido y siguiente
                    clave = tuple(sorted([ultimo_valido, siguiente]))
                    if clave in self.puertas:
                        # abrir y aplicar 2 de daño (regla: puerta sufre 2)
                        self.puertas[clave]['abierta'] = True
                        # aplicar daño a ambos lados
                        self.danar_pared_entre(ultimo_valido, siguiente, amount=2)
                    else:
                        # pared normal: aplicar 1 de daño
                        self.danar_pared_entre(ultimo_valido, siguiente, amount=1)
                    break

                # Si la casilla siguiente tiene fuego -> "saltar" sobre ella (avanzar)
                if self.tieneFuegoEn(siguiente):
                    ultimo_valido = siguiente
                    cx += dx
                    cy += dy
                    continue

                # Si la casilla tiene humo -> se convierte en fuego y terminamos en esa casilla
                if siguiente in self.posicionesHumo:
                    self.posicionesHumo.discard(siguiente)
                    self.posicionesFuego.add(siguiente)
                    # marcar daño visual en la celda
                    self.posicionesDano.add(siguiente)
                    break

                # Si la casilla está vacía o tiene agentes → ponemos fuego ahí
                # (no saltamos más)
                self.posicionesFuego.add(siguiente)
                # marcar daño visual en la celda (por efecto explosión)
                self.posicionesDano.add(siguiente)

                # AÑADIDO: Verificar si hay bomberos en la casilla y hacerlos respawnear
                agents_in_cell = self.grid.get_cell_list_contents([siguiente])
                for agent in agents_in_cell:
                    if hasattr(agent, 'respawnear_en_base'):
                        agent.respawnear_en_base()

                # Si al crear fuego esta casilla era POI -> aplicar consecuencias
                if siguiente in self.posicionesPOI:
                    if siguiente in self.civiles_revelados:
                        self.civiles_perdidos += 1
                        del self.civiles_revelados[siguiente]
                        self.posicionesPOI.remove(siguiente)
                        if len(self.posicionesPOI) < 3:
                            self.generar_nuevo_poi()
                    else:
                        self.posicionesPOI.remove(siguiente)
                        if len(self.posicionesPOI) < 3:
                            self.generar_nuevo_poi()
                break


    def danar_pared_entre(self, pos1, pos2, amount=1):
        """Aplica 'amount' puntos de daño a la pared entre dos celdas.
        Si hay puerta entre ellas, la abre y aplica daño (amount o 2 si se indica).
        """
        x1, y1 = pos1
        x2, y2 = pos2

        # Determinar dirección desde pos1 hacia pos2
        if x2 > x1:
            lado = 'derecha'
            lado_opuesto = 'izquierda'
        elif x2 < x1:
            lado = 'izquierda'
            lado_opuesto = 'derecha'
        elif y2 > y1:
            lado = 'abajo'
            lado_opuesto = 'arriba'
        elif y2 < y1:
            lado = 'arriba'
            lado_opuesto = 'abajo'
        else:
            return  # misma celda

        # Si hay puerta entre pos1 y pos2
        clave = tuple(sorted([pos1, pos2]))
        if clave in self.puertas:
            # Abrir la puerta y aplicar daño: puertas sufren 2 de daño según regla del usuario.
            self.puertas[clave]['abierta'] = True
            # Aplicar daño en ambos lados de la puerta (para simular daño a ambos muros)
            self.paredes_dano[(x1, y1)][lado] = self.paredes_dano[(x1, y1)].get(lado, 0) + amount
            # también a la celda opuesta
            self.paredes_dano[(x2, y2)][lado_opuesto] = self.paredes_dano[(x2, y2)].get(lado_opuesto, 0) + amount
            return

        # Pared "normal": aplicar damage en el lado correspondiente de pos1
        if (x1, y1) in self.paredes_dano:
            self.paredes_dano[(x1, y1)][lado] = self.paredes_dano[(x1, y1)].get(lado, 0) + amount





    def generar_fuego(self):
        """Función principal de generación de fuego"""
        self.generar_humo_aleatorio()  # Genera humo en una celda aleatoria
        self.verificarExplosiones()


    def step(self):
        """Ejecuta un paso de la simulación"""

        # Si ya terminó, no sigas avanzando
        if self.done:
            return

        # 1. Ejecutar agentes y generar fuego
        for agent in list(self.schedule):
            agent.step()
            self.generar_fuego()

        # 2. Verificar derrota
        terminado, razon = self.verificar_game_over()
        if terminado:
            print(f"GAME OVER: {razon}")
            self.done = True
            self.outcome = "lose"
            self.end_reason = razon

            if self.civiles_perdidos >= 4:
                self.end_code = "lose_civiles"
            elif self.puntos_dano >= 25:
                self.end_code = "lose_colapso"
            else:
                self.end_code = "lose_otro"

            self.running = False
            return

        # 2.5 Verificar victoria (7 civiles rescatados)
        if self.is_all_collected():
            print("VICTORIA: Se rescataron 7 civiles")
            self.done = True
            self.outcome = "win"
            self.end_reason = "Se rescataron al menos 7 civiles"
            self.end_code = "win_civiles"
            self.running = False
            return

        # 3. Recolectar datos
        self.datacollector.collect(self)

        # 4. Contador de pasos
        self.steps += 1

    def step_micro(self):
        """
        Ejecuta un 'micro paso' de la simulación:
        - Cada bombero hace SOLO UNA acción (step_micro).
        - Se genera fuego/humo una sola vez.
        - Se revisan condiciones de victoria/derrota.
        """

        # Si ya terminó la simulación, no avanzar más
        if getattr(self, "done", False):
            return

        # 1. Ejecutar micro-step de cada agente
        for agent in list(self.schedule):
            if hasattr(agent, "step_micro"):
                agent.step_micro()
            else:
                agent.step()  # fallback, por si hay agentes viejos

        # 1.5 Generar fuego/humo una vez por micro paso
        self.generar_fuego()

        # 2. Verificar condiciones de derrota
        terminado, razon = self.verificar_game_over()
        if terminado:
            print(f"GAME OVER: {razon}")
            # Si ya agregaste done/outcome/end_code/end_reason, márcalos aquí:
            self.done = True
            self.outcome = "lose"
            self.end_reason = razon

            if "4 civiles" in razon:
                self.end_code = "lose_civiles"
            elif "Edificio colapsado" in razon:
                self.end_code = "lose_colapso"
            else:
                self.end_code = "lose_other"

            self.running = False
            return

        # 2.5 Verificar condición de victoria (si ya tienes is_all_collected)
        if hasattr(self, "is_all_collected") and self.is_all_collected():
            print("VICTORIA: Se rescataron 7 civiles")
            self.done = True
            self.outcome = "win"
            self.end_reason = "Se rescataron al menos 7 civiles"
            self.end_code = "win_civiles"
            self.running = False
            return

        # 3. Recolectar datos (si usas datacollector)
        if hasattr(self, "datacollector"):
            self.datacollector.collect(self)

        # 4. Contador de pasos
        self.steps += 1


def get_grid(model):
    """
    Genera una matriz numérica basada en el estado del modelo.

    Códigos:
    0 = vacío
    1 = POI (punto de interés sin revelar)
    2 = bombero
    3 = base
    4 = humo
    5 = fuego
    6 = civil revelado
    """
    grid = np.zeros((model.grid.width, model.grid.height))

    for content, (x, y) in model.grid.coord_iter():
        # Orden de prioridad
        if (x, y) in model.posicionesFuego:
            grid[x][y] = 5  # Fuego
        elif (x, y) in model.posicionesHumo:
            grid[x][y] = 4  # Humo
        elif (x, y) in model.base_position:
            grid[x][y] = 3  # Base
        elif (x, y) in model.civiles_revelados and model.civiles_revelados[(x, y)]:
            grid[x][y] = 6  # Civil revelado
        elif (x, y) in model.posicionesPOI:
            grid[x][y] = 1  # POI sin revelar
        elif content:  # Hay un bombero
            grid[x][y] = 2  # Bombero
        else:
            grid[x][y] = 0  # Vacío

    return grid


def visualizar_tablero(model, ax=None, step_num=0):
    """
    Visualiza el estado actual del tablero
    """
    if ax is None:
        fig, ax = plt.subplots(figsize=(12, 8))
    else:
        ax.clear()

    for x in range(model.grid.width):
        for y in range(model.grid.height):
            color = "white"

            # BASES (pueden ser múltiples)
            if (x, y) in model.base_position:
                color = "yellow"
            # FUEGO
            elif (x, y) in model.posicionesFuego:
                color = "orange"
            # HUMO
            elif (x, y) in model.posicionesHumo:
                color = "gray"
            # CIVIL REVELADO
            elif (x, y) in model.civiles_revelados and model.civiles_revelados[(x, y)]:
                color = "lightblue"
            # POI (sin revelar)
            elif (x, y) in model.posicionesPOI:
                color = "lightgreen"

            rect = patches.Rectangle((x, y), 1, 1,
                                     linewidth=0.5,
                                     edgecolor="gray",
                                     facecolor=color,
                                     alpha=0.7)
            ax.add_patch(rect)

            # Texto civil revelado
            if (x, y) in model.civiles_revelados and model.civiles_revelados[(x, y)]:
                ax.text(x+0.5, y+0.5, "C", ha="center", va="center",
                        fontsize=12, fontweight="bold", color="blue")

            # Texto POI
            elif (x, y) in model.posicionesPOI:
                ax.text(x+0.5, y+0.5, "?", ha="center", va="center",
                        fontsize=14, fontweight="bold", color="green")

            # Texto base (múltiples bases)
            if (x, y) in model.base_position:
                ax.text(x+0.5, y+0.5, "BASE",
                        ha="center", va="center",
                        fontsize=10, fontweight="bold")

    # BOMBEROS
    for agent in model.schedule:
        x, y = agent.pos

        # Color diferente si está herido
        color_bombero = 'orange' if agent.herido else 'red'
        circle = patches.Circle((x+0.5, y+0.5), 0.3,
                                color=color_bombero, alpha=0.8)
        ax.add_patch(circle)

        texto = "B+C" if agent.tieneCivil else "B"
        if agent.herido:
            texto = "B!"  # Bombero herido

        ax.text(x+0.5, y+0.5, texto,
                ha="center", va="center",
                fontsize=10, color="white",
                fontweight="bold")

    # PAREDES (con indicación de daño)
    for (x, y), paredes in model.paredes.items():
        danos = model.paredes_dano.get((x, y), {})

        if paredes.get("arriba"):
            grosor = 3 if danos.get("arriba", 0) < 2 else 1
            estilo = '-' if danos.get("arriba", 0) < 2 else ':'
            ax.plot([x, x+1], [y, y], "k"+estilo, linewidth=grosor)
        if paredes.get("abajo"):
            grosor = 3 if danos.get("abajo", 0) < 2 else 1
            estilo = '-' if danos.get("abajo", 0) < 2 else ':'
            ax.plot([x, x+1], [y+1, y+1], "k"+estilo, linewidth=grosor)
        if paredes.get("izquierda"):
            grosor = 3 if danos.get("izquierda", 0) < 2 else 1
            estilo = '-' if danos.get("izquierda", 0) < 2 else ':'
            ax.plot([x, x], [y, y+1], "k"+estilo, linewidth=grosor)
        if paredes.get("derecha"):
            grosor = 3 if danos.get("derecha", 0) < 2 else 1
            estilo = '-' if danos.get("derecha", 0) < 2 else ':'
            ax.plot([x+1, x+1], [y, y+1], "k"+estilo, linewidth=grosor)

    # PUERTAS
    for (celda1, celda2), puerta_info in model.puertas.items():
        x1, y1 = celda1
        x2, y2 = celda2

        color = "green" if puerta_info["abierta"] else "brown"
        estilo = "--" if puerta_info["abierta"] else "-"
        grosor = 4 if puerta_info["abierta"] else 5

        if x1 == x2:  # horizontal
            y_p = (y1 + y2) / 2 + 0.5
            ax.plot([x1, x1+1], [y_p, y_p], color=color, linestyle=estilo, linewidth=grosor)
        else:         # vertical
            x_p = (x1 + x2) / 2 + 0.5
            ax.plot([x_p, x_p], [y1, y1+1], color=color, linestyle=estilo, linewidth=grosor)

    ax.set_xlim(0, model.grid.width)
    ax.set_ylim(0, model.grid.height)
    ax.set_aspect("equal")
    ax.invert_yaxis()
    ax.set_title(f"Flash Point - Step {step_num}")

    if ax is None:
        plt.tight_layout()
        plt.show()

import copy
import pandas as pd
import matplotlib.pyplot as plt

def ejecutar_simulacion_con_animacion(tipo_agente, max_steps=100, archivo_config='config.txt'):
    """
    Ejecuta simulación guardando UN frame por step (más eficiente)
    """
    model = Tablero(width=8, height=6, num_agentes=6,
                   tipo_agente=tipo_agente, archivo_config=archivo_config)

    history_models = []
    history_models.append(copy.deepcopy(model))

    print(f"Iniciando simulación...")
    print(f"Agentes: {len(model.schedule)}")
    print(f"Civiles iniciales: {np.sum(model.cells == 3)}")
    print(f"Fuegos iniciales: {len(model.posicionesFuego)}")

    for step in range(max_steps):
        if step % 10 == 0:
            print(f"  Step {step}...")

        model.step()
        # Guardar solo UN frame por step (en lugar de uno por acción)
        history_models.append(copy.deepcopy(model))

        # Verificar condiciones de término
        game_over, razon = model.verificar_game_over()
        if game_over:
            print(f"¡DERROTA! Razón: {razon} en step {step}")
            break

        if model.is_all_collected():
            print(f"¡VICTORIA! 7 civiles rescatados en step {step}!")
            break

    print(f"\nSimulación completada:")
    print(f"  Total frames: {len(history_models)}")
    print(f"  Steps ejecutados: {model.steps}")
    print(f"  Civiles rescatados: {model.civiles_rescatados}")
    print(f"  Civiles perdidos: {model.civiles_perdidos}")
    print(f"  POI restantes: {len(model.posicionesPOI)}")
    print(f"  Fuegos apagados: {sum(a.apagarFuego for a in model.schedule)}")
    print(f"  Humos apagados: {sum(a.apagarHumo for a in model.schedule)}")
    print(f"  Puntos de daño: {model.puntos_dano}")
    print(f"  Explosiones generadas: {model.explosiones_generadas}")

    game_over, razon = model.verificar_game_over()
    if game_over:
        print(f"  Resultado: DERROTA ({razon})")
    elif model.is_all_collected():
        print(f"  Resultado: VICTORIA")
    else:
        print(f"  Resultado: Simulación incompleta")

    return history_models


def ejecutar_simulacion_detallada(tipo_agente, max_steps=30, archivo_config='config.txt',
                                   frames_por_agente=False):
    """
    Ejecuta simulación con control de frames
    Si frames_por_agente=True, guarda frame por movimiento (muchos frames)
    Si frames_por_agente=False, guarda frame por step (menos frames)
    """
    model = Tablero(width=8, height=6, num_agentes=6,
                   tipo_agente=tipo_agente, archivo_config=archivo_config)

    history_models = []
    history_models.append(copy.deepcopy(model))

    print(f"Ejecutando simulación detallada...")
    print(f"Agentes: {len(model.schedule)}")
    print(f"Civiles iniciales: {np.sum(model.cells == 3)}")

    for step in range(max_steps):
        if step % 5 == 0:
            print(f"  Step {step}...")

        if frames_por_agente:
            # Guardar frame por cada agente
            for agent in model.schedule:
                agent.step()
                model.generar_fuego()
                history_models.append(copy.deepcopy(model))
            model.steps += 1
            model.datacollector.collect(model)
        else:
            # Guardar solo un frame por step completo
            model.step()
            history_models.append(copy.deepcopy(model))

        # Verificar condiciones de término
        game_over, razon = model.verificar_game_over()
        if game_over or model.is_all_collected():
            print(f"  Terminó en step {step}")
            break

    print(f"\nSimulación completada:")
    print(f"  Frames totales: {len(history_models)}")
    print(f"  Steps ejecutados: {model.steps}")
    print(f"  Civiles rescatados: {model.civiles_rescatados}")
    print(f"  Civiles perdidos: {model.civiles_perdidos}")
    print(f"  Fuegos apagados: {sum(a.apagarFuego for a in model.schedule)}")

    return history_models


def comparar_estrategias(archivo_config='config.txt', num_simulaciones=10):
    """
    Compara estrategias aleatoria vs inteligente
    MODIFICADO: Ahora también cuenta y grafica derrotas
    """
    resultados_aleatorio = []
    resultados_inteligente = []

    print("\nComparando estrategias con", num_simulaciones, "simulaciones...")

    for i in range(num_simulaciones):
        print(f"  Simulación {i+1}/{num_simulaciones}")

        try:
            # Estrategia aleatoria
            model_random = Tablero(width=8, height=6, num_agentes=6,
                                  tipo_agente=BomberoAleatorio,
                                  archivo_config=archivo_config)

            for step in range(100):
                model_random.step()
                game_over, razon = model_random.verificar_game_over()
                if model_random.is_all_collected() or game_over:
                    break

            # MODIFICADO: Determinar resultado
            game_over, razon = model_random.verificar_game_over()
            victoria = model_random.is_all_collected()
            derrota = game_over

            resultados_aleatorio.append({
                'civiles_rescatados': model_random.civiles_rescatados,
                'civiles_perdidos': model_random.civiles_perdidos,
                'victoria': victoria,
                'derrota': derrota,  # AÑADIDO
                'razon_derrota': razon if derrota else None,  # AÑADIDO
                'steps': model_random.steps,
                'puertas_abiertas': sum(1 for p in model_random.puertas.values() if p['abierta']),
                'puntos_dano': model_random.puntos_dano,
                'fuegos_apagados': sum(a.apagarFuego for a in model_random.schedule),
                'humos_apagados': sum(a.apagarHumo for a in model_random.schedule),
                'explosiones_generadas': model_random.explosiones_generadas
            })

        except Exception as e:
            print(f"    Error en simulación aleatoria {i+1}: {e}")
            resultados_aleatorio.append({
                'civiles_rescatados': 0, 'civiles_perdidos': 4,
                'victoria': False, 'derrota': True, 'razon_derrota': 'Error',
                'steps': 100, 'puertas_abiertas': 0,
                'puntos_dano': 25, 'fuegos_apagados': 0, 'humos_apagados': 0,
                'explosiones_generadas': 0
            })

        try:
            # Estrategia inteligente
            model_smart = Tablero(width=8, height=6, num_agentes=6,
                                tipo_agente=Bombero,
                                archivo_config=archivo_config)

            for step in range(100):
                model_smart.step()
                game_over, razon = model_smart.verificar_game_over()
                if model_smart.is_all_collected() or game_over:
                    break

            # MODIFICADO: Determinar resultado
            game_over, razon = model_smart.verificar_game_over()
            victoria = model_smart.is_all_collected()
            derrota = game_over

            resultados_inteligente.append({
                'civiles_rescatados': model_smart.civiles_rescatados,
                'civiles_perdidos': model_smart.civiles_perdidos,
                'victoria': victoria,
                'derrota': derrota,  # AÑADIDO
                'razon_derrota': razon if derrota else None,  # AÑADIDO
                'steps': model_smart.steps,
                'puertas_abiertas': sum(1 for p in model_smart.puertas.values() if p['abierta']),
                'puntos_dano': model_smart.puntos_dano,
                'fuegos_apagados': sum(a.apagarFuego for a in model_smart.schedule),
                'humos_apagados': sum(a.apagarHumo for a in model_smart.schedule),
                'explosiones_generadas': model_smart.explosiones_generadas
            })

        except Exception as e:
            print(f"    Error en simulación inteligente {i+1}: {e}")
            resultados_inteligente.append({
                'civiles_rescatados': 0, 'civiles_perdidos': 4,
                'victoria': False, 'derrota': True, 'razon_derrota': 'Error',
                'steps': 100, 'puertas_abiertas': 0,
                'puntos_dano': 25, 'fuegos_apagados': 0, 'humos_apagados': 0,
                'explosiones_generadas': 0
            })

    # Crear DataFrames
    df_aleatorio = pd.DataFrame(resultados_aleatorio)
    df_inteligente = pd.DataFrame(resultados_inteligente)

    if df_aleatorio.empty or df_inteligente.empty:
        print("Error: DataFrames vacíos")
        return df_aleatorio, df_inteligente

    # Mostrar estadísticas
    print("\n=== RESULTADOS COMPARATIVOS ===")
    print("\nEstrategia Aleatoria:")
    print(df_aleatorio.describe())
    print("\nEstrategia Inteligente:")
    print(df_inteligente.describe())

    # MODIFICADO: Gráficas comparativas (3x3 grid) con victorias Y derrotas
    fig, axes = plt.subplots(3, 3, figsize=(18, 15))

    # Fila 1
    # Civiles rescatados
    axes[0, 0].boxplot([df_aleatorio['civiles_rescatados'].values,
                     df_inteligente['civiles_rescatados'].values],
                    labels=['Aleatorio', 'Inteligente'])
    axes[0, 0].set_title('Civiles Rescatados')
    axes[0, 0].set_ylabel('Cantidad')
    axes[0, 0].grid(True, alpha=0.3)

    # Civiles perdidos
    axes[0, 1].boxplot([df_aleatorio['civiles_perdidos'].values,
                     df_inteligente['civiles_perdidos'].values],
                    labels=['Aleatorio', 'Inteligente'])
    axes[0, 1].set_title('Civiles Perdidos')
    axes[0, 1].set_ylabel('Cantidad')
    axes[0, 1].grid(True, alpha=0.3)

    # MODIFICADO: Victorias Y Derrotas (gráfica de barras agrupadas)
    victorias_aleatorio = df_aleatorio['victoria'].sum()
    victorias_inteligente = df_inteligente['victoria'].sum()
    derrotas_aleatorio = df_aleatorio['derrota'].sum()
    derrotas_inteligente = df_inteligente['derrota'].sum()

    x = np.arange(2)  # Aleatorio, Inteligente
    width = 0.35

    bars1 = axes[0, 2].bar(x - width/2, [victorias_aleatorio, victorias_inteligente],
                           width, label='Victorias', color='green', alpha=0.7)
    bars2 = axes[0, 2].bar(x + width/2, [derrotas_aleatorio, derrotas_inteligente],
                           width, label='Derrotas', color='red', alpha=0.7)

    axes[0, 2].set_xticks(x)
    axes[0, 2].set_xticklabels(['Aleatorio', 'Inteligente'])
    axes[0, 2].set_title('Victorias vs Derrotas')
    axes[0, 2].set_ylabel('Cantidad')
    axes[0, 2].legend()
    axes[0, 2].grid(True, alpha=0.3, axis='y')

    # Añadir etiquetas de valor en las barras
    for bar in bars1:
        height = bar.get_height()
        axes[0, 2].annotate(f'{int(height)}',
                           xy=(bar.get_x() + bar.get_width() / 2, height),
                           xytext=(0, 3), textcoords="offset points",
                           ha='center', va='bottom', fontsize=10)
    for bar in bars2:
        height = bar.get_height()
        axes[0, 2].annotate(f'{int(height)}',
                           xy=(bar.get_x() + bar.get_width() / 2, height),
                           xytext=(0, 3), textcoords="offset points",
                           ha='center', va='bottom', fontsize=10)

    # Fila 2
    # Pasos necesarios
    axes[1, 0].boxplot([df_aleatorio['steps'].values,
                     df_inteligente['steps'].values],
                    labels=['Aleatorio', 'Inteligente'])
    axes[1, 0].set_title('Pasos Necesarios')
    axes[1, 0].set_ylabel('Steps')
    axes[1, 0].grid(True, alpha=0.3)

    # Puntos de daño
    axes[1, 1].boxplot([df_aleatorio['puntos_dano'].values,
                     df_inteligente['puntos_dano'].values],
                    labels=['Aleatorio', 'Inteligente'])
    axes[1, 1].set_title('Puntos de Daño')
    axes[1, 1].set_ylabel('Daño')
    axes[1, 1].grid(True, alpha=0.3)

    # Puertas abiertas
    axes[1, 2].boxplot([df_aleatorio['puertas_abiertas'].values,
                     df_inteligente['puertas_abiertas'].values],
                    labels=['Aleatorio', 'Inteligente'])
    axes[1, 2].set_title('Puertas Abiertas')
    axes[1, 2].set_ylabel('Cantidad')
    axes[1, 2].grid(True, alpha=0.3)

    # Fila 3
    # Fuegos apagados
    axes[2, 0].boxplot([df_aleatorio['fuegos_apagados'].values,
                     df_inteligente['fuegos_apagados'].values],
                    labels=['Aleatorio', 'Inteligente'])
    axes[2, 0].set_title('Fuegos Apagados')
    axes[2, 0].set_ylabel('Cantidad')
    axes[2, 0].grid(True, alpha=0.3)

    # Humos apagados
    axes[2, 1].boxplot([df_aleatorio['humos_apagados'].values,
                     df_inteligente['humos_apagados'].values],
                    labels=['Aleatorio', 'Inteligente'])
    axes[2, 1].set_title('Humos Apagados')
    axes[2, 1].set_ylabel('Cantidad')
    axes[2, 1].grid(True, alpha=0.3)

    # AÑADIDO: Gráfica de razones de derrota
    razones_aleatorio = df_aleatorio[df_aleatorio['derrota'] == True]['razon_derrota'].value_counts()
    razones_inteligente = df_inteligente[df_inteligente['derrota'] == True]['razon_derrota'].value_counts()

    # Combinar todas las razones posibles
    todas_razones = list(set(list(razones_aleatorio.index) + list(razones_inteligente.index)))
    todas_razones = [r for r in todas_razones if r is not None]

    if todas_razones:
        x_razones = np.arange(len(todas_razones))
        width_razones = 0.35

        vals_aleatorio = [razones_aleatorio.get(r, 0) for r in todas_razones]
        vals_inteligente = [razones_inteligente.get(r, 0) for r in todas_razones]

        axes[2, 2].bar(x_razones - width_razones/2, vals_aleatorio, width_razones,
                       label='Aleatorio', color='blue', alpha=0.7)
        axes[2, 2].bar(x_razones + width_razones/2, vals_inteligente, width_razones,
                       label='Inteligente', color='orange', alpha=0.7)
        axes[2, 2].set_xticks(x_razones)
        axes[2, 2].set_xticklabels(todas_razones, rotation=45, ha='right')
        axes[2, 2].set_title('Razones de Derrota')
        axes[2, 2].set_ylabel('Cantidad')
        axes[2, 2].legend()
        axes[2, 2].grid(True, alpha=0.3, axis='y')
    else:
        axes[2, 2].text(0.5, 0.5, '¡No hubo derrotas!',
                        ha='center', va='center', fontsize=14, color='green')
        axes[2, 2].set_title('Razones de Derrota')
        axes[2, 2].axis('off')

    plt.suptitle('Comparación de Estrategias', fontsize=16, fontweight='bold')
    plt.tight_layout()
    plt.show()

    # Calcular mejoras
    mejora_civiles = ((df_inteligente['civiles_rescatados'].mean() -
                      df_aleatorio['civiles_rescatados'].mean()) /
                     max(df_aleatorio['civiles_rescatados'].mean(), 0.001) * 100)

    mejora_fuegos = ((df_inteligente['fuegos_apagados'].mean() -
                     df_aleatorio['fuegos_apagados'].mean()) /
                    max(df_aleatorio['fuegos_apagados'].mean(), 0.001) * 100)

    # MODIFICADO: Mostrar estadísticas incluyendo derrotas
    print(f"\n=== MEJORA DE LA ESTRATEGIA INTELIGENTE ===")
    print(f"Victorias (Aleatorio): {victorias_aleatorio}/{num_simulaciones}")
    print(f"Victorias (Inteligente): {victorias_inteligente}/{num_simulaciones}")
    print(f"Derrotas (Aleatorio): {derrotas_aleatorio}/{num_simulaciones}")
    print(f"Derrotas (Inteligente): {derrotas_inteligente}/{num_simulaciones}")
    print(f"\nCiviles rescatados (Aleatorio): {df_aleatorio['civiles_rescatados'].mean():.2f}")
    print(f"Civiles rescatados (Inteligente): {df_inteligente['civiles_rescatados'].mean():.2f}")
    print(f"Mejora en rescates: {mejora_civiles:.1f}%")
    print(f"\nCiviles perdidos (Aleatorio): {df_aleatorio['civiles_perdidos'].mean():.2f}")
    print(f"Civiles perdidos (Inteligente): {df_inteligente['civiles_perdidos'].mean():.2f}")
    print(f"\nFuegos apagados (Aleatorio): {df_aleatorio['fuegos_apagados'].mean():.2f}")
    print(f"Fuegos apagados (Inteligente): {df_inteligente['fuegos_apagados'].mean():.2f}")
    print(f"Mejora en combate: {mejora_fuegos:.1f}%")

    # AÑADIDO: Mostrar razones de derrota
    print(f"\n=== RAZONES DE DERROTA ===")
    print("Aleatorio:")
    for razon, count in razones_aleatorio.items():
        print(f"  - {razon}: {count}")
    print("Inteligente:")
    for razon, count in razones_inteligente.items():
        print(f"  - {razon}: {count}")

    return df_aleatorio, df_inteligente


# ============================================
# CELDA 5: CORRECCIÓN EN BomberoAleatorio
# Quitar la lógica de "herido" ya que ahora respawnea
# ============================================
"""
INSTRUCCIONES: REEMPLAZAR el método step() de BomberoAleatorio por este:
"""

class BomberoAleatorio(Bombero):
    def step(self):
        self.energia_actual = self.energia_maxima + self.energia_guardada
        self.energia_guardada = 0

        # Entregar civil en base
        if self.pos in self.model.base_position and self.tieneCivil:
            self.tieneCivil = False
            self.model.civiles_rescatados += 1

        # ELIMINADO: Ya no necesita lógica de "herido" porque respawnea automáticamente
        # El método respawnear_en_base() se llama desde generar_humo_aleatorio()

        while self.energia_actual > 0:
            # Usar np.random para probabilidades
            accion = np.random.choice(['mover', 'puerta', 'fuego', 'humo', 'nada'],
                                     p=[0.5, 0.15, 0.15, 0.1, 0.1])

            if accion == 'mover':
                self.movimiento_aleatorio()
            elif accion == 'puerta':
                vecinos = list(self.get_neighbors())
                if vecinos:
                    vecino = vecinos[np.random.randint(len(vecinos))]
                    if self.model.hay_puerta_entre(self.pos, vecino):
                        self.abrir_puerta(self.pos, vecino)
                    else:
                        self.gastar_energia()
                else:
                    self.gastar_energia()
            elif accion == 'fuego':
                if not self.apagar_fuego():
                    self.gastar_energia()
            elif accion == 'humo':
                if not self.apagar_humo():
                    self.gastar_energia()
            else:
                self.gastar_energia()

        if self.energia_actual > 0:
            self.energia_guardada = min(self.energia_actual, self.energia_maxima)

import matplotlib.animation as animation
import matplotlib.patches as patches
from matplotlib.lines import Line2D

def animar_simulacion(history_models, interval=200):
    """
    Crea animación básica de la simulación (un frame por step)
    """
    fig, ax = plt.subplots(figsize=(10, 6))

    def update(frame):
        ax.clear()
        model = history_models[frame]

        # Dibujar celdas
        for x in range(model.grid.width):
            for y in range(model.grid.height):
                color = 'white'

                # BASES (múltiples)
                if (x, y) in model.base_position:
                    color = 'yellow'
                # FUEGO
                elif (x, y) in model.posicionesFuego:
                    color = 'orange'
                # HUMO
                elif (x, y) in model.posicionesHumo:
                    color = 'gray'
                # CIVIL REVELADO
                elif (x, y) in model.civiles_revelados and model.civiles_revelados[(x, y)]:
                    color = 'lightblue'
                # POI (sin revelar)
                elif (x, y) in model.posicionesPOI:
                    color = 'lightgreen'

                rect = patches.Rectangle((x, y), 1, 1,
                                        linewidth=0.5,
                                        edgecolor='gray',
                                        facecolor=color,
                                        alpha=0.7)
                ax.add_patch(rect)

                # Texto civil revelado
                if (x, y) in model.civiles_revelados and model.civiles_revelados[(x, y)]:
                    ax.text(x+0.5, y+0.5, 'C',
                           ha='center', va='center',
                           fontsize=12, fontweight='bold', color='blue')

                # Texto POI
                elif (x, y) in model.posicionesPOI:
                    ax.text(x+0.5, y+0.5, '?',
                           ha='center', va='center',
                           fontsize=14, fontweight='bold', color='green')

                # Texto base (múltiples bases)
                if (x, y) in model.base_position:
                    ax.text(x+0.5, y+0.5, 'BASE',
                           ha='center', va='center',
                           fontsize=10, fontweight='bold')

        # Dibujar bomberos
        for i, agent in enumerate(model.schedule):
            x, y = agent.pos

            # Color diferente si está herido
            color_bombero = 'orange' if agent.herido else 'red'
            circle = patches.Circle((x+0.5, y+0.5), 0.3,
                                   color=color_bombero, alpha=0.8)
            ax.add_patch(circle)

            texto = f"B{i+1}"
            if agent.herido:
                texto = f"B{i+1}!"
            elif agent.tieneCivil:
                texto += "+C"

            ax.text(x+0.5, y+0.5, texto,
                   ha='center', va='center',
                   fontsize=8 if (agent.tieneCivil or agent.herido) else 10,
                   color='white', fontweight='bold')

        # Dibujar paredes (con daño)
        for (x, y), paredes in model.paredes.items():
            danos = model.paredes_dano.get((x, y), {})

            if paredes.get('arriba', False):
                damage = danos.get('arriba', 0)
                grosor = 1 if damage >= 2 else 3
                estilo = '--' if damage >= 2 else '-'
                color_pared = 'silver' if damage >= 2 else 'k'
                ax.plot([x, x+1], [y, y], color=color_pared, linestyle=estilo, linewidth=grosor)
            if paredes.get('abajo', False):
                damage = danos.get('abajo', 0)
                grosor = 1 if damage >= 2 else 3
                estilo = '--' if damage >= 2 else '-'
                color_pared = 'silver' if damage >= 2 else 'k'
                ax.plot([x, x+1], [y+1, y+1], color=color_pared, linestyle=estilo, linewidth=grosor)
            if paredes.get('izquierda', False):
                damage = danos.get('izquierda', 0)
                grosor = 1 if damage >= 2 else 3
                estilo = '--' if damage >= 2 else '-'
                color_pared = 'silver' if damage >= 2 else 'k'
                ax.plot([x, x], [y, y+1], color=color_pared, linestyle=estilo, linewidth=grosor)
            if paredes.get('derecha', False):
                damage = danos.get('derecha', 0)
                grosor = 1 if damage >= 2 else 3
                estilo = '--' if damage >= 2 else '-'
                color_pared = 'silver' if damage >= 2 else 'k'
                ax.plot([x+1, x+1], [y, y+1], color=color_pared, linestyle=estilo, linewidth=grosor)

        # Dibujar puertas
        for (celda1, celda2), puerta_info in model.puertas.items():
            x1, y1 = celda1
            x2, y2 = celda2

            if puerta_info['abierta']:
                color = 'green'
                estilo = '--'
                grosor = 4
            else:
                color = 'brown'
                estilo = '-'
                grosor = 5

            if x1 == x2:
                y_puerta = (y1 + y2) / 2 + 0.5
                ax.plot([x1, x1+1], [y_puerta, y_puerta],
                       color=color, linestyle=estilo, linewidth=grosor)
            else:
                x_puerta = (x1 + x2) / 2 + 0.5
                ax.plot([x_puerta, x_puerta], [y1, y1+1],
                       color=color, linestyle=estilo, linewidth=grosor)

        # Configuración
        ax.set_xlim(0, model.grid.width)
        ax.set_ylim(0, model.grid.height)
        ax.set_aspect('equal')
        ax.invert_yaxis()
        ax.set_xticks(range(model.grid.width + 1))
        ax.set_yticks(range(model.grid.height + 1))
        ax.grid(True, alpha=0.2, linestyle=':')

        ax.set_title(f'Flash Point: Fire Rescue - Frame {frame}/{len(history_models)-1}',
                    fontsize=14, fontweight='bold')

        return []

    anim = animation.FuncAnimation(
        fig, update,
        frames=len(history_models),
        interval=interval,
        repeat=True
    )

    plt.tight_layout()
    return anim


def animar_simulacion_detallada(history_models, interval=100):
    """
    Crea animación con información adicional (acción por acción)
    """
    fig, ax = plt.subplots(figsize=(16, 9))  # Increased figure width

    def update(frame):
        ax.clear()
        model = history_models[frame]

        # Dibujar celdas
        for x in range(model.grid.width):
            for y in range(model.grid.height):
                color = 'white'

                if (x, y) in model.base_position:
                    color = 'yellow'
                elif (x, y) in model.posicionesFuego:
                    color = 'orange'
                elif (x, y) in model.posicionesHumo:
                    color = 'gray'
                elif (x, y) in model.civiles_revelados and model.civiles_revelados[(x, y)]:
                    color = 'lightblue'
                elif (x, y) in model.posicionesPOI:
                    color = 'lightgreen'

                rect = patches.Rectangle((x, y), 1, 1,
                                        linewidth=0.5,
                                        edgecolor='gray',
                                        facecolor=color,
                                        alpha=0.7)
                ax.add_patch(rect)

                if (x, y) in model.civiles_revelados and model.civiles_revelados[(x, y)]:
                    ax.text(x+0.5, y+0.5, 'C',
                           ha='center', va='center',
                           fontsize=12, fontweight='bold', color='blue')
                elif (x, y) in model.posicionesPOI:
                    ax.text(x+0.5, y+0.5, '?',
                           ha='center', va='center',
                           fontsize=14, fontweight='bold', color='green')

                if (x, y) in model.base_position:
                    ax.text(x+0.5, y+0.5, 'BASE',
                           ha='center', va='center',
                           fontsize=10, fontweight='bold')

        # Dibujar bomberos
        for i, agent in enumerate(model.schedule):
            x, y = agent.pos

            # Color diferente si está herido
            color_bombero = 'orange' if agent.herido else 'red'
            circle = patches.Circle((x+0.5, y+0.5), 0.3,
                                   color=color_bombero, alpha=0.8)
            ax.add_patch(circle)

            texto = f"B{i+1}"
            if agent.herido:
                texto = f"B{i+1}!"
            elif agent.tieneCivil:
                texto += "+C"

            ax.text(x+0.5, y+0.5, texto,
                   ha='center', va='center',
                   fontsize=8 if (agent.tieneCivil or agent.herido) else 10,
                   color='white', fontweight='bold')

        # Dibujar paredes (con daño)
        for (x, y), paredes in model.paredes.items():
            danos = model.paredes_dano.get((x, y), {})

            if paredes.get('arriba', False):
                damage = danos.get('arriba', 0)
                grosor = 1 if damage >= 2 else 3
                estilo = '--' if damage >= 2 else '-'
                color_pared = 'silver' if damage >= 2 else 'k'
                ax.plot([x, x+1], [y, y], color=color_pared, linestyle=estilo, linewidth=grosor)
            if paredes.get('abajo', False):
                damage = danos.get('abajo', 0)
                grosor = 1 if damage >= 2 else 3
                estilo = '--' if damage >= 2 else '-'
                color_pared = 'silver' if damage >= 2 else 'k'
                ax.plot([x, x+1], [y+1, y+1], color=color_pared, linestyle=estilo, linewidth=grosor)
            if paredes.get('izquierda', False):
                damage = danos.get('izquierda', 0)
                grosor = 1 if damage >= 2 else 3
                estilo = '--' if damage >= 2 else '-'
                color_pared = 'silver' if damage >= 2 else 'k'
                ax.plot([x, x], [y, y+1], color=color_pared, linestyle=estilo, linewidth=grosor)
            if paredes.get('derecha', False):
                damage = danos.get('derecha', 0)
                grosor = 1 if damage >= 2 else 3
                estilo = '--' if damage >= 2 else '-'
                color_pared = 'silver' if damage >= 2 else 'k'
                ax.plot([x+1, x+1], [y, y+1], color=color_pared, linestyle=estilo, linewidth=grosor)

        # Dibujar puertas
        for (celda1, celda2), puerta_info in model.puertas.items():
            x1, y1 = celda1
            x2, y2 = celda2

            if puerta_info['abierta']:
                color = 'green'
                estilo = '--'
                grosor = 4
            else:
                color = 'brown'
                estilo = '-'
                grosor = 5

            if x1 == x2:
                y_puerta = (y1 + y2) / 2 + 0.5
                ax.plot([x1, x1+1], [y_puerta, y_puerta],
                       color=color, linestyle=estilo, linewidth=grosor)
            else:
                x_puerta = (x1 + x2) / 2 + 0.5
                ax.plot([x_puerta, x_puerta], [y1, y1+1],
                       color=color, linestyle=estilo, linewidth=grosor)

        # Configuración
        ax.set_xlim(0, model.grid.width)
        ax.set_ylim(0, model.grid.height)
        ax.set_aspect('equal')
        ax.invert_yaxis()
        ax.set_xticks(range(model.grid.width + 1))
        ax.set_yticks(range(model.grid.height + 1))
        ax.grid(True, alpha=0.2, linestyle=':')

        ax.set_title(f'Flash Point: Fire Rescue - Frame {frame}/{len(history_models)-1}',
                    fontsize=14, fontweight='bold')

        # Información adicional
        civiles_rescatados = model.civiles_rescatados
        civiles_revelados_no_rescatados = sum(1 for v in model.civiles_revelados.values() if v)
        poi_sin_revelar = len(model.posicionesPOI) - civiles_revelados_no_rescatados
        puertas_abiertas = sum(1 for p in model.puertas.values() if p['abierta'])

        # Adjust info_text position to avoid overlap with main plot
        info_text = ax.text(model.grid.width + 0.5, model.grid.height * 0.7, # Adjusted x and y coordinates
                          (
                           f'Step: {model.steps}\n'
                           f'Civiles rescatados: {civiles_rescatados}/7\n'
                           f'Civiles perdidos: {model.civiles_perdidos}/4\n'
                           f'Civiles revelados: {civiles_revelados_no_rescatados}\n'
                           f'POI sin revelar: {poi_sin_revelar}\n'
                           f'Puertas abiertas: {puertas_abiertas}\n'
                           f'Fuegos activos: {len(model.posicionesFuego)}\n'
                           f'Puntos de daño: {model.puntos_dano}/25\n'
                           f'Explosines generadas:{model.explosiones_generadas}'
                          ),
                           fontsize=10,
                           bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.8))

        # Leyenda
        legend_elements = [
            Line2D([0], [0], marker='o', color='w', markerfacecolor='red',
                   markersize=10, label='Bombero'),
            Line2D([0], [0], marker='o', color='w', markerfacecolor='orange',
                   markersize=10, label='Bombero Herido'),
            Line2D([0], [0], marker='s', color='w', markerfacecolor='lightgreen',
                   markersize=10, label='POI (?)'),
            Line2D([0], [0], marker='s', color='w', markerfacecolor='lightblue',
                   markersize=10, label='Civil Revelado'),
            Line2D([0], [0], marker='s', color='w', markerfacecolor='yellow',
                   markersize=10, label='Base'),
            Line2D([0], [0], marker='s', color='w', markerfacecolor='orange',
                   markersize=10, label='Fuego'),
            Line2D([0], [0], marker='s', color='w', markerfacecolor='gray',
                   markersize=10, label='Humo'),
            Line2D([0], [0], color='black', linewidth=3, label='Pared'),
            Line2D([0], [0], color='silver', linewidth=1, linestyle='--', label='Pared Destruida'),
            Line2D([0], [0], color='brown', linewidth=4, label='Puerta Cerrada'),
            Line2D([0], [0], color='green', linewidth=4, linestyle='--',
                   label='Puerta Abierta')
        ]
        # Adjusted bbox_to_anchor to position the legend to the right of the plot
        ax.legend(handles=legend_elements, loc='upper left',
                 bbox_to_anchor=(1.05, 1), fontsize=8)

        return []

    anim = animation.FuncAnimation(
        fig, update,
        frames=len(history_models),
        interval=interval,
        repeat=True
    )

    plt.tight_layout()
    return anim

def ejecutar_simulacion_accion_por_accion(tipo_agente, max_steps=50, archivo_config='config.txt'):
    """
    Ejecuta simulación guardando UN FRAME POR CADA ACCIÓN de cada agente
    ¡ADVERTENCIA! Genera MUCHOS frames (puede ser lento)
    """
    model = Tablero(width=8, height=6, num_agentes=6,
                   tipo_agente=tipo_agente, archivo_config=archivo_config)

    history_models = []
    history_models.append(copy.deepcopy(model))

    print(f"🎬 Ejecutando simulación ACCIÓN POR ACCIÓN...")
    print(f"Agentes: {len(model.schedule)}")
    print(f"Civiles iniciales (POI): {len(model.posicionesPOI)}")
    print(f"⚠️  Esto generará MUCHOS frames (puede tardar)")

    for step in range(max_steps):
        if step % 5 == 0:
            print(f"  Step {step}... (frames: {len(history_models)})")

        # Procesar cada agente individualmente
        for agent_idx, agent in enumerate(model.schedule):
            # Resetear energía
            agent.energia_actual = agent.energia_maxima + agent.energia_guardada
            agent.energia_guardada = 0
            agent.celdas_exploradas.add(agent.pos)

            # Si está en base con civil, entregarlo
            if agent.pos in model.base_position and agent.tieneCivil:

                agent.tieneCivil = False
                model.civiles_rescatados += 1
                history_models.append(copy.deepcopy(model))

            # Ejecutar cada acción del agente
            acciones_realizadas = 0
            while agent.energia_actual > 0 and acciones_realizadas < 15:  # Límite de seguridad
                pos_antes = agent.pos
                energia_antes = agent.energia_actual
                fuego_antes = len(model.posicionesFuego)
                humo_antes = len(model.posicionesHumo)
                civil_antes = agent.tieneCivil
                pois_antes = len(model.posicionesPOI)

                # Ejecutar UNA acción según tipo de agente
                if type(agent).__name__ == 'BomberoAleatorio':
                    # Bombero aleatorio
                    accion = np.random.choice(['mover', 'puerta', 'fuego', 'humo', 'nada'],
                                             p=[0.5, 0.15, 0.15, 0.1, 0.1])

                    if accion == 'mover':
                        agent.movimiento_aleatorio()
                    elif accion == 'puerta':
                        vecinos = list(agent.get_neighbors())
                        if vecinos:
                            vecino = vecinos[np.random.randint(len(vecinos))]
                            if model.hay_puerta_entre(agent.pos, vecino):
                                agent.abrir_puerta(agent.pos, vecino)
                            else:
                                agent.gastar_energia()
                        else:
                            agent.gastar_energia()
                    elif accion == 'fuego':
                        if not agent.apagar_fuego():
                            agent.gastar_energia()
                    elif accion == 'humo':
                        if not agent.apagar_humo():
                            agent.gastar_energia()
                    else:
                        agent.gastar_energia()
                else:
                    # Bombero inteligente - ejecutar UNA acción
                    accion_realizada = False

                    # PRIORIDAD 1: Apagar fuego
                    if model.tieneFuegoEn(agent.pos):
                        accion_realizada = agent.apagar_fuego()
                        if accion_realizada:
                            history_models.append(copy.deepcopy(model))
                            acciones_realizadas += 1
                            continue

                    # PRIORIDAD 2: Apagar humo
                    if model.tieneHumoEn(agent.pos):
                        accion_realizada = agent.apagar_humo()
                        if accion_realizada:
                            history_models.append(copy.deepcopy(model))
                            acciones_realizadas += 1
                            continue

                   # PRIORIDAD 3: Si tiene civil, ir a base MÁS CERCANA
                    if agent.tieneCivil:
                        # CORRECCIÓN: usar "not in" para lista de bases
                        if agent.pos not in model.base_position:
                            # Encontrar la base más cercana
                            bases_con_distancia = []
                            for base in model.base_position:
                                camino = agent.buscar_camino_bfs(base)
                                if camino is not None:
                                    bases_con_distancia.append((base, len(camino)))

                            if bases_con_distancia:
                                base_mas_cercana = min(bases_con_distancia, key=lambda x: x[1])[0]
                                accion_realizada = agent.mover_hacia(base_mas_cercana)
                            else:
                                accion_realizada = agent.gastar_energia()
                        else:
                            # Ya está en base, entregar civil
                            agent.tieneCivil = False
                            model.civiles_rescatados += 1
                            accion_realizada = True
                            history_models.append(copy.deepcopy(model))
                            acciones_realizadas += 1
                            continue
                    else:
                        # PRIORIDAD 4: Buscar civil revelado
                        civil_objetivo = agent.encontrar_civil_revelado_mas_cercano()
                        if civil_objetivo:
                            accion_realizada = agent.mover_hacia(civil_objetivo)
                        else:
                            # PRIORIDAD 5: Buscar POI
                            poi_objetivo = agent.encontrar_poi_mas_cercano()
                            if poi_objetivo:
                                accion_realizada = agent.mover_hacia(poi_objetivo)
                            else:
                                # PRIORIDAD 6: Combatir fuego
                                fuego_objetivo = agent.encontrar_fuego_mas_cercano()
                                if fuego_objetivo:
                                    accion_realizada = agent.mover_hacia(fuego_objetivo)
                                else:
                                    accion_realizada = agent.movimiento_aleatorio()

                    if not accion_realizada:
                        agent.gastar_energia()

                # Si hubo cambio significativo, guardar frame
                cambio_significativo = (
                    agent.pos != pos_antes or
                    agent.energia_actual != energia_antes or
                    agent.tieneCivil != civil_antes or
                    len(model.posicionesFuego) != fuego_antes or
                    len(model.posicionesHumo) != humo_antes or
                    len(model.posicionesPOI) != pois_antes
                )

                if cambio_significativo:
                    history_models.append(copy.deepcopy(model))

                acciones_realizadas += 1

            # Guardar energía sobrante
            if agent.energia_actual > 0:
                agent.energia_guardada = min(agent.energia_actual, agent.energia_maxima)

            # Generar fuego después de cada agente
            fuegos_antes = len(model.posicionesFuego)
            model.generar_fuego()

            # Guardar frame si el fuego cambió
            if len(model.posicionesFuego) != fuegos_antes:
                history_models.append(copy.deepcopy(model))

        # Incrementar contador
        model.steps += 1
        model.datacollector.collect(model)

        # Verificar condiciones de término
        game_over, razon = model.verificar_game_over()
        if game_over:
            print(f"  ¡DERROTA! {razon} en step {step}")
            break

        if model.is_all_collected():
            print(f"  ¡VICTORIA! 7 civiles rescatados en step {step}")
            break

    # Frame final
    history_models.append(copy.deepcopy(model))

    print(f"\n✅ Simulación completada:")
    print(f"  Frames totales: {len(history_models)}")
    print(f"  Steps ejecutados: {model.steps}")
    print(f"  Civiles rescatados: {model.civiles_rescatados}")
    print(f"  Civiles perdidos: {model.civiles_perdidos}")
    print(f"  Fuegos apagados: {sum(a.apagarFuego for a in model.schedule)}")

    return history_models

# ==========================================
# CREAR ARCHIVO DE CONFIGURACIÓN
# ==========================================
if __name__ == "__main__":
    config_text = """1001 1000 1100 1001 1100 1001 1000 1100
    0001 0000 0110 0011 0110 0011 0010 0110
    0001 0100 1001 1000 1000 1100 1001 1100
    0011 0110 0011 0010 0010 0110 0011 0110
    1001 1000 1000 1000 1100 1001 1100 1101
    0011 0010 0010 0010 0110 0011 0110 0111
    2 4 v
    5 1 f
    5 8 v
    2 2
    2 3
    3 2
    3 3
    3 4
    3 5
    4 4
    5 6
    5 7
    6 6
    1 3 1 4
    2 5 2 6
    2 8 3 8
    3 2 3 3
    4 4 5 4
    4 6 4 7
    6 5 6 6
    6 7 6 8
    1 6
    3 1
    4 8
    6 3"""

    with open('config.txt', 'w') as f:
        f.write(config_text)

    print("✅ Archivo de configuración creado")

    # ==========================================
    # 1. EJECUTAR SIMULACIONES BÁSICAS
    # ==========================================
    print("\n" + "="*50)
    print("FLASH POINT: FIRE RESCUE")
    print("="*50)

    # Ejecutar simulación inteligente
    print("\n📊 Ejecutando estrategia INTELIGENTE...")
    history_smart = ejecutar_simulacion_con_animacion(
        tipo_agente=Bombero,
        max_steps=100,
        archivo_config='config.txt'
    )

    # Ejecutar simulación aleatoria
    print("\n🎲 Ejecutando estrategia ALEATORIA...")
    history_random = ejecutar_simulacion_con_animacion(
        tipo_agente=BomberoAleatorio,
        max_steps=100,
        archivo_config='config.txt'
    )

    # ==========================================
    # 2. COMPARAR ESTRATEGIAS (10 SIMULACIONES)
    # ==========================================
    print("\n" + "="*50)
    print("COMPARACIÓN DE ESTRATEGIAS")
    print("="*50)

    df_aleatorio, df_inteligente = comparar_estrategias(
        archivo_config='config.txt',
        num_simulaciones=10
    )

    # ==========================================
    # 3. SIMULACIÓN ACCIÓN POR ACCIÓN (⚠️ MUCHOS FRAMES)
    # ==========================================
    print("\n" + "="*50)
    print("SIMULACIÓN ACCIÓN POR ACCIÓN")
    print("="*50)

    print("\n📊 Estrategia Inteligente (ACCIÓN POR ACCIÓN):")
    history_accion_smart = ejecutar_simulacion_accion_por_accion(
        tipo_agente=Bombero,
        max_steps=20,  # Menos steps porque genera MUCHOS frames
        archivo_config='config.txt'
    )

    # ==========================================
    # 4. CREAR ANIMACIONES
    # ==========================================
    print("\n" + "="*50)
    print("CREANDO ANIMACIONES")
    print("="*50)

    # Animación básica (un frame por step) - RÁPIDA
    print("\n🎬 Creando animación básica (1 frame/step)...")
    anim_basica = animar_simulacion(history_smart, interval=300)

    # Animación detallada (acción por acción) - LENTA pero completa
    print("🎬 Creando animación detallada (acción por acción)...")
    anim_detallada = animar_simulacion_detallada(history_accion_smart, interval=100)

    # ==========================================
    # 5. MOSTRAR ANIMACIÓN EN JUPYTER
    # ==========================================
    from IPython.display import HTML

    print("\n✅ Todo listo! Mostrando animación...")
    print(f"Frames animación básica: {len(history_smart)}")
    print(f"Frames animación detallada: {len(history_accion_smart)}")
    print("\n⚠️  La animación detallada puede tardar en cargar...")

    # OPCIÓN 1: Mostrar animación básica (más rápida)
    # HTML(anim_basica.to_jshtml())

    # OPCIÓN 2: Mostrar animación detallada (acción por acción)
    HTML(anim_detallada.to_jshtml())

    # ==========================================
    # OPCIONAL: GUARDAR COMO GIF
    # ==========================================
    # Descomenta las siguientes líneas si quieres guardar como GIF:
    # print("\n💾 Guardando animación como GIF...")
    # anim_detallado.save('simulacion_detallada.gif', writer='pillow', fps=10)
    # print("✅ GIF guardado como 'simulacion_detallada.gif'")