# -*- coding: utf-8 -*-
"""Copy of Firefightersreal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OU-y_58IqfaE31EvQYHLlgy4rr1nJO56
"""

#!pip install numpy scipy matplotlib seaborn scikit-learn mesa -q

from mesa import Agent, Model
from mesa.space import MultiGrid
from mesa.datacollection import DataCollector
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import matplotlib.patches as patches
from matplotlib.lines import Line2D
import numpy as np
import pandas as pd
import copy
from collections import deque

from mesa import Agent
from collections import deque
import numpy as np

class Bombero(Agent):
    def __init__(self, model, energia_maxima=4):
        super().__init__(model)

        self.visited = 0
        self.apagarFuego = 0
        self.apagarHumo = 0
        self.civilesRes = 0
        self.puertas_abiertas = 0
        self.energia_maxima = energia_maxima
        self.energia_actual = energia_maxima
        self.energia_guardada = 0
        self.tieneCivil = False
        self.celdas_exploradas = set()
        self.ultimo_objetivo = None

    def puede_moverse(self, desde, hacia):
        if not self.model.hay_pared_entre(desde, hacia):
            return True
        if self.model.hay_puerta_entre(desde, hacia):
            return self.model.esta_puerta_abierta(desde, hacia)
        return False

    def abrir_puerta(self, desde, hacia):
        if self.energia_actual < 1:
            return False
        if self.model.hay_puerta_entre(desde, hacia):
            if not self.model.esta_puerta_abierta(desde, hacia):
                key = tuple(sorted([desde, hacia]))
                self.model.puertas[key]['abierta'] = True
                self.energia_actual -= 1
                self.puertas_abiertas += 1
                return True
        return False

    def apagar_fuego(self):
        """Apaga el fuego en la celda actual (cuesta 1 energía)"""
        if self.energia_actual < 1:
            return False
        if self.model.tieneFuegoEn(self.pos):
            self.model.quitarFuego(self.pos)
            self.energia_actual -= 1
            self.apagarFuego += 1
            return True
        return False

    def apagar_humo(self):
        """Apaga el humo en la celda actual (cuesta 1 energía)"""
        if self.energia_actual < 1:
            return False
        if self.model.tieneHumoEn(self.pos):
            self.model.quitarHumo(self.pos)
            self.energia_actual -= 1
            self.apagarHumo += 1
            return True
        return False

    def gastar_energia(self, cantidad=1):
        if self.energia_actual >= cantidad:
            self.energia_actual -= cantidad
            return True
        return False

    def get_neighbors(self):
        return self.model.grid.get_neighborhood(
            self.pos, moore=False, include_center=False
        )

    def buscar_camino_bfs(self, objetivo):
        if self.pos == objetivo:
            return []
        visitados = {self.pos}
        cola = deque([(self.pos, [])])

        while cola:
            actual, camino = cola.popleft()
            vecinos = self.model.grid.get_neighborhood(
                actual, moore=False, include_center=False
            )
            for vecino in vecinos:
                if vecino not in visitados:
                    puede_pasar = self.puede_moverse(actual, vecino)
                    hay_puerta = self.model.hay_puerta_entre(actual, vecino)
                    if puede_pasar or hay_puerta:
                        nuevo_camino = camino + [vecino]
                        if vecino == objetivo:
                            return nuevo_camino
                        visitados.add(vecino)
                        cola.append((vecino, nuevo_camino))
        return None

    def encontrar_poi_mas_cercano(self):
        """Encuentra el POI (punto de interés) más cercano"""
        pois = []
        for pos in self.model.posicionesPOI:
            camino = self.buscar_camino_bfs(pos)
            if camino is not None:
                pois.append((pos, len(camino)))
        if not pois:
            return None
        poi_cercano = min(pois, key=lambda x: x[1])
        return poi_cercano[0]

    def encontrar_civil_revelado_mas_cercano(self):
        """Encuentra el civil ya revelado más cercano"""
        civiles = []
        for pos, revelado in self.model.civiles_revelados.items():
            if revelado:  # Solo civiles revelados
                camino = self.buscar_camino_bfs(pos)
                if camino is not None:
                    civiles.append((pos, len(camino)))
        if not civiles:
            return None
        return min(civiles, key=lambda x: x[1])[0]

    def encontrar_fuego_mas_cercano(self):
        """Encuentra el fuego más cercano"""
        fuegos = []
        for pos in self.model.posicionesFuego:
            camino = self.buscar_camino_bfs(pos)
            if camino is not None:
                fuegos.append((pos, len(camino)))
        if not fuegos:
            return None
        return min(fuegos, key=lambda x: x[1])[0]

    def mover_hacia(self, objetivo):
        if self.energia_actual < 1:
            return False
        camino = self.buscar_camino_bfs(objetivo)
        if not camino:
            return False
        siguiente = camino[0]

        if self.puede_moverse(self.pos, siguiente):
            self.model.grid.move_agent(self, siguiente)
            self.visited += 1
            self.energia_actual -= 1
            self.celdas_exploradas.add(siguiente)

            # Verificar si llegó a un POI
            if self.model.is_poi(siguiente):
                tipo = self.model.revelar_poi(siguiente)
                if tipo == 'civil':
                    # Recoger civil
                    self.model.quitar_civil(siguiente)
                    self.civilesRes += 1
                    self.tieneCivil = True
                # Si es falsa alarma, no hace nada (ya se removió del tablero)
            return True

        elif self.model.hay_puerta_entre(self.pos, siguiente):
            if not self.model.esta_puerta_abierta(self.pos, siguiente):
                return self.abrir_puerta(self.pos, siguiente)
        return False

    def base_mas_cercana(self):
      """Retorna la base más cercana según BFS."""
      mejores = []

      for base in self.model.base_position:
          camino = self.buscar_camino_bfs(base)
          if camino is not None:
              mejores.append((base, len(camino)))

      if not mejores:
          return None

      base_cercana = min(mejores, key=lambda x: x[1])
      return base_cercana[0]

    def movimiento_aleatorio(self):
        if self.energia_actual < 1:
            return False
        vecinos = list(self.get_neighbors())
        if not vecinos:
            return self.gastar_energia()
        np.random.shuffle(vecinos)

        for vecino in vecinos:
            if self.puede_moverse(self.pos, vecino):
                self.model.grid.move_agent(self, vecino)
                self.visited += 1
                self.energia_actual -= 1

                # Verificar si llegó a un POI
                if self.model.is_poi(vecino):
                    tipo = self.model.revelar_poi(vecino)
                    if tipo == 'civil':
                        self.model.quitar_civil(vecino)
                        self.civilesRes += 1
                        self.tieneCivil = True
                return True

        for vecino in vecinos:
            if self.model.hay_puerta_entre(self.pos, vecino):
                if not self.model.esta_puerta_abierta(self.pos, vecino):
                    return self.abrir_puerta(self.pos, vecino)

        return self.gastar_energia()

    def step(self):
        self.energia_actual = self.energia_maxima + self.energia_guardada
        self.energia_guardada = 0
        self.celdas_exploradas.add(self.pos)

        if self.pos in self.model.base_position and self.tieneCivil:
            self.tieneCivil = False
            self.model.civiles_rescatados += 1 # Increment only on delivery

        while self.energia_actual > 0:
            accion_realizada = False

            # PRIORIDAD 1: Apagar fuego en posición actual
            if self.model.tieneFuegoEn(self.pos):
                accion_realizada = self.apagar_fuego()
                if accion_realizada:
                    continue

            # PRIORIDAD 2: Apagar humo en posición actual
            if self.model.tieneHumoEn(self.pos):
                accion_realizada = self.apagar_humo()
                if accion_realizada:
                    continue

            # PRIORIDAD 3: Si tiene civil, ir a la base
            if self.tieneCivil:
                base = self.base_mas_cercana()
                if base is not None and self.pos != base:
                    accion_realizada = self.mover_hacia(base)
                else:
                    accion_realizada = self.gastar_energia()
            else:
                # PRIORIDAD 4: Buscar civil revelado
                civil_objetivo = self.encontrar_civil_revelado_mas_cercano()
                if civil_objetivo:
                    accion_realizada = self.mover_hacia(civil_objetivo)
                else:
                    # PRIORIDAD 5: Buscar POI no revelado
                    poi_objetivo = self.encontrar_poi_mas_cercano()
                    if poi_objetivo:
                        accion_realizada = self.mover_hacia(poi_objetivo)
                    else:
                        # PRIORIDAD 6: Combatir fuego
                        fuego_objetivo = self.encontrar_fuego_mas_cercano()
                        if fuego_objetivo:
                            accion_realizada = self.mover_hacia(fuego_objetivo)
                        else:
                            accion_realizada = self.movimiento_aleatorio()

            if not accion_realizada:
                self.gastar_energia()

        if self.energia_actual > 0:
            self.energia_guardada = min(self.energia_actual, self.energia_maxima)


class BomberoAleatorio(Bombero):
    def step(self):
        self.energia_actual = self.energia_maxima + self.energia_guardada
        self.energia_guardada = 0

        if self.pos in self.model.base_position and self.tieneCivil:
            self.tieneCivil = False
            self.model.civiles_rescatados += 1 # Increment only on delivery

        while self.energia_actual > 0:
            # Usar np.random para probabilidades
            accion = np.random.choice(['mover', 'puerta', 'fuego', 'humo', 'nada'],
                                     p=[0.5, 0.15, 0.15, 0.1, 0.1])

            if accion == 'mover':
                self.movimiento_aleatorio()
            elif accion == 'puerta':
                vecinos = list(self.get_neighbors())
                if vecinos:
                    vecino = vecinos[np.random.randint(len(vecinos))]
                    if self.model.hay_puerta_entre(self.pos, vecino):
                        self.abrir_puerta(self.pos, vecino)
                    else:
                        self.gastar_energia()
                else:
                    self.gastar_energia()
            elif accion == 'fuego':
                if not self.apagar_fuego():
                    self.gastar_energia()
            elif accion == 'humo':
                if not self.apagar_humo():
                    self.gastar_energia()
            else:
                self.gastar_energia()

        if self.energia_actual > 0:
            self.energia_guardada = min(self.energia_actual, self.energia_maxima)

def get_grid(model):
    """
    Genera una matriz numérica basada en el estado del modelo.

    Códigos:
    0 = vacío
    1 = POI (punto de interés sin revelar)
    2 = bombero
    3 = base
    4 = humo
    5 = fuego
    6 = civil revelado
    """
    grid = np.zeros((model.grid.width, model.grid.height))

    for content, (x, y) in model.grid.coord_iter():
        # Orden de prioridad
        if (x, y) in model.posicionesFuego:
            grid[x][y] = 5  # Fuego
        elif (x, y) in model.posicionesHumo:
            grid[x][y] = 4  # Humo
        elif (x, y) in model.base_position:
            grid[x][y] = 3  # Base
        elif (x, y) in model.civiles_revelados and model.civiles_revelados[(x, y)]:
            grid[x][y] = 6  # Civil revelado
        elif (x, y) in model.posicionesPOI:
            grid[x][y] = 1  # POI sin revelar
        elif content:  # Hay un bombero
            grid[x][y] = 2  # Bombero
        else:
            grid[x][y] = 0  # Vacío

    return grid

from mesa import Model
from mesa.space import MultiGrid

import numpy as np

class Tablero(Model):
    def __init__(self, width=8, height=6, num_agentes=6, tipo_agente=None, archivo_config=None):
        super().__init__()

        self.grid = MultiGrid(width, height, torus=False)
        self.schedule = []
        self.current_id = 0
        self.base_position = [(6,0),(0,3),(9,4),(3,7)]
        self.cells = np.zeros((width, height))  # Ya no usaremos esto para civiles
        self.paredes = {}
        self.puertas = {}
        self.paredes_dano = {}  # Nuevo: daño en paredes
        self.steps = 0
        self.civiles_rescatados = 0
        self.civiles_perdidos = 0
        self.puntos_dano = 0
        self.tipo_agente = tipo_agente

        # Sistema de POI (Puntos de Interés)
        self.posicionesPOI = set()  # POI visibles en el tablero (siempre 3)
        self.poi_sin_revelar = []   # Lista de (pos, tipo) donde tipo='v' o 'f'
        self.civiles_revelados = {}  # {pos: True} - civiles que ya fueron revelados
        self.falsas_alarmas_reveladas = set()  # posiciones de falsas alarmas reveladas

        # Estados del fuego/humo/daño
        self.posicionesFuego = set()
        self.posicionesHumo = set()
        self.posicionesDano = set()

        self.datacollector = DataCollector(
            model_reporters={
                "Civiles_rescatados": lambda m: m.civiles_rescatados,
                "Civiles_perdidos": lambda m: m.civiles_perdidos,
                "POI_activos": lambda m: len(m.posicionesPOI),
                "Puertas_abiertas": lambda m: sum(1 for p in m.puertas.values() if p.get('abierta')),
                "Steps": lambda m: m.steps,
                "Fuegos_Activos": lambda m: len(m.posicionesFuego),
                "Humo_Activos": lambda m: len(m.posicionesHumo),
                "Puntos_Dano": lambda m: m.puntos_dano
            },
            agent_reporters={
                "Civiles": lambda a: a.civilesRes,
                "Visitadas": lambda a: a.visited,
                "Fuegos_Apagados": lambda a: a.apagarFuego,
            }
        )

        if archivo_config:
            self.cargar_configuracion(archivo_config)
        else:
            self.configuracion_default()

        # Colocar 3 POI iniciales
        self.colocar_poi_iniciales()

        for i in range(num_agentes):
            self.agregar_bombero()

        self.datacollector.collect(self)

    def agregar_bombero(self):
        """Agrega un bombero en posición válida"""
        intentos = 0
        max_intentos = 100

        while intentos < max_intentos:
            x = self.random.randrange(self.grid.width)
            y = self.random.randrange(self.grid.height)

            if (self.grid.is_cell_empty((x, y)) and
                (x, y) not in self.base_position and # Changed to 'not in'
                (x, y) not in self.posicionesPOI and
                (x, y) not in self.posicionesFuego):

                try:
                    bombero = self.tipo_agente(self)
                    self.grid.place_agent(bombero, (x, y))
                    self.schedule.append(bombero)
                    return True
                except Exception as e:
                    print(f"Error al agregar bombero en ({x},{y}): {e}")
                    pass

            intentos += 1

        print(f"Advertencia: No se pudo colocar bombero después de {max_intentos} intentos")
        return False

    def cargar_configuracion(self, archivo):
        with open(archivo, 'r') as f:
            lines = [line.strip() for line in f.readlines() if line.strip()]

        idx = 0

        # 1. Cargar paredes (6 líneas)
        for row in range(6):
            if idx >= len(lines):
                break
            line_parts = lines[idx].split()
            for col in range(min(8, len(line_parts))):
                wall_config = line_parts[col]
                if len(wall_config) == 4:
                    self.paredes[(col, row)] = {
                        'arriba': wall_config[0] == '1',
                        'derecha': wall_config[1] == '1',
                        'abajo': wall_config[2] == '1',
                        'izquierda': wall_config[3] == '1'
                    }
                    # Inicializar daño en paredes
                    self.paredes_dano[(col, row)] = {
                        'arriba': 0, 'izquierda': 0, 'abajo': 0, 'derecha': 0
                    }
            idx += 1

        # 2. Cargar POI (3 líneas iniciales, pero crearemos pool de 15)
        poi_iniciales = []
        for _ in range(3):
            if idx >= len(lines):
                break
            parts = lines[idx].split()
            if len(parts) >= 3:
                row = int(parts[0]) - 1
                col = int(parts[1]) - 1
                tipo = parts[2]  # 'v' o 'f'
                if 0 <= row < 6 and 0 <= col < 8:
                    poi_iniciales.append(((col, row), tipo))
            idx += 1

        # Crear pool de 15 POI (10 civiles, 5 falsas alarmas)
        # Los primeros 3 del archivo + 12 aleatorios
        self.poi_sin_revelar = poi_iniciales.copy()

        # Generar 12 POI adicionales aleatorios
        civiles_necesarios = 10 - sum(1 for _, tipo in poi_iniciales if tipo == 'v')
        falsas_necesarias = 5 - sum(1 for _, tipo in poi_iniciales if tipo == 'f')

        posiciones_ocupadas = {pos for pos, _ in poi_iniciales}
        for pos in self.base_position: # Changed to iterate through base_position
            posiciones_ocupadas.add(pos)

        # Generar civiles
        for _ in range(civiles_necesarios):
            while True:
                x = self.random.randrange(self.grid.width)
                y = self.random.randrange(self.grid.height)
                if (x, y) not in posiciones_ocupadas:
                    self.poi_sin_revelar.append(((x, y), 'v'))
                    posiciones_ocupadas.add((x, y))
                    break

        # Generar falsas alarmas
        for _ in range(falsas_necesarias):
            while True:
                x = self.random.randrange(self.grid.width)
                y = self.random.randrange(self.grid.height)
                if (x, y) not in posiciones_ocupadas:
                    self.poi_sin_revelar.append(((x, y), 'f'))
                    posiciones_ocupadas.add((x, y))
                    break

        # Mezclar el pool
        self.random.shuffle(self.poi_sin_revelar)

        # 3. Cargar posiciones iniciales de fuego (10 líneas)
        for _ in range(10):
            if idx >= len(lines):
                break
            parts = lines[idx].split()
            if len(parts) >= 2:
                row = int(parts[0]) - 1
                col = int(parts[1]) - 1
                if 0 <= row < 6 and 0 <= col < 8:
                    self.posicionesFuego.add((col, row))
            idx += 1

        # 4. Cargar puertas (8 líneas)
        for _ in range(8):
            if idx >= len(lines):
                break
            parts = lines[idx].split()
            if len(parts) >= 4:
                r1 = int(parts[0]) - 1
                c1 = int(parts[1]) - 1
                r2 = int(parts[2]) - 1
                c2 = int(parts[3]) - 1
                if (0 <= r1 < 6 and 0 <= c1 < 8 and 0 <= r2 < 6 and 0 <= c2 < 8):
                    celda1 = (c1, r1)
                    celda2 = (c2, r2)
                    key = tuple(sorted([celda1, celda2]))
                    self.puertas[key] = {'abierta': False}
            idx += 1

    def colocar_poi_iniciales(self):
        """Coloca 3 POI en el tablero desde el pool"""
        for _ in range(min(3, len(self.poi_sin_revelar))):
            if self.poi_sin_revelar:
                pos, tipo = self.poi_sin_revelar.pop(0)
                # Si hay fuego en esa posición, no colocar ahí
                if pos not in self.posicionesFuego:
                    self.posicionesPOI.add(pos)
                    # Guardar el tipo para cuando se revele
                    if tipo == 'v':
                        self.civiles_revelados[pos] = False  # No revelado aún
                    # Las falsas alarmas no necesitan tracking especial

    def generar_nuevo_poi(self):
        """Genera un nuevo POI en posición válida"""
        if not self.poi_sin_revelar:
            return  # No hay más POI disponibles

        intentos = 0
        while intentos < 50 and self.poi_sin_revelar:
            pos, tipo = self.poi_sin_revelar.pop(0)

            # Verificar que no haya fuego
            if pos not in self.posicionesFuego and pos not in self.posicionesPOI:
                self.posicionesPOI.add(pos)
                if tipo == 'v':
                    self.civiles_revelados[pos] = False
                return
            else:
                # Si había fuego, generar otro
                intentos += 1

        # Si no pudimos colocar, poner en posición aleatoria válida
        if self.poi_sin_revelar:
            pos, tipo = self.poi_sin_revelar.pop(0)
            intentos = 0
            while intentos < 100:
                x = self.random.randrange(self.grid.width)
                y = self.random.randrange(self.grid.height)
                if ((x, y) not in self.posicionesFuego and
                    (x, y) not in self.posicionesPOI and
                    (x, y) not in self.base_position): # Changed to 'not in'
                    self.posicionesPOI.add((x, y))
                    if tipo == 'v':
                        self.civiles_revelados[(x, y)] = False
                    return
                intentos += 1

    def configuracion_default(self):
        for x in range(self.grid.width):
            for y in range(self.grid.height):
                self.paredes[(x, y)] = {
                    'arriba': y == 0,
                    'abajo': y == self.grid.height - 1,
                    'izquierda': x == 0,
                    'derecha': x == self.grid.width - 1
                }
                self.paredes_dano[(x, y)] = {
                    'arriba': 0, 'izquierda': 0, 'abajo': 0, 'derecha': 0
                }

    def hay_pared_entre(self, celda1, celda2):
        """Verifica si hay pared entre dos celdas (considerando daño)"""
        x1, y1 = celda1
        x2, y2 = celda2

        if abs(x1 - x2) + abs(y1 - y2) != 1:
            return False

        direccion = None
        if x2 > x1:
            direccion = 'derecha'
        elif x2 < x1:
            direccion = 'izquierda'
        elif y2 > y1:
            direccion = 'abajo'
        elif y2 < y1:
            direccion = 'arriba'

        # Si la pared tiene 2+ de daño, está destruida
        if self.paredes_dano.get(celda1, {}).get(direccion, 0) >= 2:
            return False

        return self.paredes.get(celda1, {}).get(direccion, False)

    def hay_puerta_entre(self, celda1, celda2):
        key = tuple(sorted([celda1, celda2]))
        return key in self.puertas

    def esta_puerta_abierta(self, celda1, celda2):
        key = tuple(sorted([celda1, celda2]))
        return self.puertas.get(key, {}).get('abierta', False)

    def is_poi(self, pos):
        """Verifica si hay un POI en esta posición"""
        return pos in self.posicionesPOI

    def revelar_poi(self, pos):
        """Revela un POI: puede ser civil o falsa alarma"""
        if pos not in self.posicionesPOI:
            return None

        # Determinar si es civil o falsa alarma
        if pos in self.civiles_revelados:
            # Es un civil
            self.civiles_revelados[pos] = True  # Marcar como revelado
            return 'civil'
        else:
            # Es falsa alarma
            self.falsas_alarmas_reveladas.add(pos)
            self.posicionesPOI.remove(pos)
            # Generar nuevo POI
            if len(self.posicionesPOI) < 3:
                self.generar_nuevo_poi()
            return 'falsa_alarma'

    def quitar_civil(self, pos):
        """Marca un civil como recogido por un bombero (solo si está revelado)"""
        if pos in self.civiles_revelados and self.civiles_revelados[pos]:
            del self.civiles_revelados[pos]
            self.posicionesPOI.discard(pos)
            # The increment of civiles_rescatados is now handled in Bombero.step
            # Generar nuevo POI
            if len(self.posicionesPOI) < 3:
                self.generar_nuevo_poi()
            return True
        return False

    def is_all_collected(self):
        """Victoria: 7 civiles rescatados"""
        return self.civiles_rescatados >= 7

    def all_agents_empty(self):
        return all(not a.tieneCivil for a in self.schedule)

    def verificar_game_over(self):
        """Verifica condiciones de derrota"""
        if self.civiles_perdidos >= 4:
            return True, "4 civiles heridos"
        if self.puntos_dano >= 25:
            return True, "Edificio colapsado"
        return False, None

    # ========== MÉTODOS DE FUEGO ==========

    def tieneFuegoEn(self, pos):
        return pos in self.posicionesFuego

    def tieneHumoEn(self, pos):
        return pos in self.posicionesHumo

    def tieneDanoEn(self, pos):
        return pos in self.posicionesDano

    def obtenerPosicionesFuego(self):
        return list(self.posicionesFuego)

    def esPosicionValida(self, pos):
        x, y = pos
        return 0 <= x < self.grid.width and 0 <= y < self.grid.height

    def puedePropagar(self, origen, destino):
        """Determina si el fuego/humo puede propagarse entre dos celdas"""
        x1, y1 = origen
        x2, y2 = destino

        if not (0 <= x2 < self.grid.width and 0 <= y2 < self.grid.height):
            return False

        if x2 == x1 and y2 == y1 - 1:
            dir_origen, dir_destino = 'arriba', 'abajo'
        elif x2 == x1 and y2 == y1 + 1:
            dir_origen, dir_destino = 'abajo', 'arriba'
        elif y2 == y1 and x2 == x1 - 1:
            dir_origen, dir_destino = 'izquierda', 'derecha'
        elif y2 == y1 and x2 == x1 + 1:
            dir_origen, dir_destino = 'derecha', 'izquierda'
        else:
            return False

        # Si pared tiene 2+ daño, está destruida
        if self.paredes_dano.get((x1, y1), {}).get(dir_origen, 0) >= 2:
            return True

        # Si hay pared intacta, no se propaga
        if self.paredes.get((x1, y1), {}).get(dir_origen, False):
            return False
        if self.paredes.get((x2, y2), {}).get(dir_destino, False):
            return False

        # Si hay puerta
        clave = tuple(sorted([origen, destino]))
        if clave in self.puertas:
            return self.puertas[clave]['abierta']

        return True

    def propagarFuego(self):
        """Propaga fuego con probabilidad del 10%"""
        nuevosFuegos = set()

        for posFuego in list(self.posicionesFuego):
            x, y = posFuego
            adyacentes = [(x-1,y), (x+1,y), (x,y-1), (x,y+1)]

            for adjPos in adyacentes:
                if (self.puedePropagar(posFuego, adjPos) and
                    not self.tieneFuegoEn(adjPos) and
                    self.random.random() < 0.10):
                    nuevosFuegos.add(adjPos)

        self.posicionesFuego.update(nuevosFuegos)

        # Verificar si fuego revela/hiere POIs
        for pos in nuevosFuegos:
            if pos in self.posicionesPOI:
                if pos in self.civiles_revelados:
                    # Civil herido
                    self.civiles_perdidos += 1
                    del self.civiles_revelados[pos]
                    self.posicionesPOI.remove(pos)
                    if len(self.posicionesPOI) < 3:
                        self.generar_nuevo_poi()
                else:
                    # Falsa alarma quemada
                    self.posicionesPOI.remove(pos)
                    if len(self.posicionesPOI) < 3:
                        self.generar_nuevo_poi()

    def quitarFuego(self, pos):
        if pos in self.posicionesFuego:
            self.posicionesFuego.remove(pos)

    def generarHumo(self):
        """Genera humo en celdas adyacentes a fuego"""
        for posFuego in list(self.posicionesFuego):
            x, y = posFuego
            adyacentes = [(x-1,y), (x+1,y), (x,y-1), (x,y+1)]

            for adjPos in adyacentes:
                if (self.esPosicionValida(adjPos) and
                    not self.tieneFuegoEn(adjPos)):
                    self.posicionesHumo.add(adjPos)

    def quitarHumo(self, pos):
        if pos in self.posicionesHumo:
            self.posicionesHumo.remove(pos)

    def verificarExplosiones(self):
        """Si una celda tiene >= 4 celdas de fuego adyacentes, explota"""
        for pos in list(self.posicionesFuego):
            x, y = pos
            fuegosAdyacentes = 0
            adyacentes = [(x-1,y), (x+1,y), (x,y-1), (x,y+1)]

            for adjPos in adyacentes:
                if self.tieneFuegoEn(adjPos):
                    fuegosAdyacentes += 1

            if fuegosAdyacentes >= 4:
                self.explosion(pos)

    def explosion(self, pos):
        """Causa daño y elimina el fuego en la celda"""
        x, y = pos
        self.puntos_dano += 2
        self.posicionesDano.add(pos)
        self.posicionesFuego.discard(pos)

        # Propagar daño con probabilidad 0.2
        adyacentes = [(x-1,y), (x+1,y), (x,y-1), (x,y+1)]
        for adjPos in adyacentes:
            if self.esPosicionValida(adjPos):
                if self.random.random() < 0.2:
                    self.posicionesDano.add(adjPos)
                    # Dañar paredes adyacentes
                    self.danar_pared_entre(pos, adjPos)

    def danar_pared_entre(self, pos1, pos2):
        """Aplica 1 punto de daño a la pared entre dos celdas"""
        x1, y1 = pos1
        x2, y2 = pos2

        if x2 > x1:
            self.paredes_dano[(x1, y1)]['derecha'] += 1
        elif x2 < x1:
            self.paredes_dano[(x1, y1)]['izquierda'] += 1
        elif y2 > y1:
            self.paredes_dano[(x1, y1)]['abajo'] += 1
        elif y2 < y1:
            self.paredes_dano[(x1, y1)]['arriba'] += 1

    def aplicarDano(self):
        """Daño aleatorio por fuego"""
        for pos in list(self.posicionesFuego):
            if self.random.random() < 0.05:
                self.puntos_dano += 1
                self.posicionesDano.add(pos)

    def generar_fuego(self):
        """Función principal de generación de fuego"""
        self.propagarFuego()
        self.generarHumo()
        self.verificarExplosiones()
        self.aplicarDano()

    def step(self):
        """Ejecuta un paso de la simulación"""
        for agent in list(self.schedule):
            agent.step()
            self.generar_fuego()

        self.datacollector.collect(self)
        self.steps += 1

def get_grid(model):
    """
    Genera una matriz numérica basada en el estado del modelo.

    Códigos:
    0 = vacío
    1 = POI (punto de interés sin revelar)
    2 = bombero
    3 = base
    4 = humo
    5 = fuego
    6 = civil revelado
    """
    grid = np.zeros((model.grid.width, model.grid.height))

    for content, (x, y) in model.grid.coord_iter():
        # Orden de prioridad
        if (x, y) in model.posicionesFuego:
            grid[x][y] = 5  # Fuego
        elif (x, y) in model.posicionesHumo:
            grid[x][y] = 4  # Humo
        elif (x, y) in model.base_position: # Changed to 'in'
            grid[x][y] = 3  # Base
        elif (x, y) in model.civiles_revelados and model.civiles_revelados[(x, y)]:
            grid[x][y] = 6  # Civil revelado
        elif (x, y) in model.posicionesPOI:
            grid[x][y] = 1  # POI sin revelar
        elif content:  # Hay un bombero
            grid[x][y] = 2  # Bombero
        else:
            grid[x][y] = 0  # Vacío

    return grid


def visualizar_tablero(model, ax=None, step_num=0):
    """
    Visualiza el estado actual del tablero
    """
    if ax is None:
        fig, ax = plt.subplots(figsize=(12, 8))
    else:
        ax.clear()

    for x in range(model.grid.width):
        for y in range(model.grid.height):
            color = "white"

            # BASE
            if (x, y) in model.base_position: # Changed to 'in'
                color = "yellow"
            # FUEGO
            elif (x, y) in model.posicionesFuego:
                color = "orange"
            # HUMO
            elif (x, y) in model.posicionesHumo:
                color = "gray"
            # CIVIL REVELADO
            elif (x, y) in model.civiles_revelados and model.civiles_revelados[(x, y)]:
                color = "lightblue"
            # POI (sin revelar)
            elif (x, y) in model.posicionesPOI:
                color = "lightgreen"

            rect = patches.Rectangle((x, y), 1, 1,
                                     linewidth=0.5,
                                     edgecolor="gray",
                                     facecolor=color,
                                     alpha=0.7)
            ax.add_patch(rect)

            # Texto civil revelado
            if (x, y) in model.civiles_revelados and model.civiles_revelados[(x, y)]:
                ax.text(x+0.5, y+0.5, "C", ha="center", va="center",
                        fontsize=12, fontweight="bold", color="blue")

            # Texto POI
            elif (x, y) in model.posicionesPOI:
                ax.text(x+0.5, y+0.5, "?", ha="center", va="center",
                        fontsize=14, fontweight="bold", color="green")

            # Texto base
            if (x, y) in model.base_position: # Changed to 'in'
                ax.text(x+0.5, y+0.5, "BASE",
                        ha="center", va="center",
                        fontsize=10, fontweight="bold")

    # BOMBEROS
    for agent in model.schedule:
        x, y = agent.pos
        circle = patches.Circle((x+0.5, y+0.5), 0.3,
                                color="red", alpha=0.8)
        ax.add_patch(circle)

        texto = "B+C" if agent.tieneCivil else "B"
        ax.text(x+0.5, y+0.5, texto,
                ha="center", va="center",
                fontsize=10, color="white",
                fontweight="bold")

    # PAREDES (con indicación de daño)
    for (x, y), paredes in model.paredes.items():
        danos = model.paredes_dano.get((x, y), {})

        if paredes.get("arriba"):
            grosor = 3 if danos.get("arriba", 0) < 2 else 1
            estilo = '-' if danos.get("arriba", 0) < 2 else ':'
            ax.plot([x, x+1], [y, y], "k"+estilo, linewidth=grosor)
        if paredes.get("abajo"):
            grosor = 3 if danos.get("abajo", 0) < 2 else 1
            estilo = '-' if danos.get("abajo", 0) < 2 else ':'
            ax.plot([x, x+1], [y+1, y+1], "k"+estilo, linewidth=grosor)
        if paredes.get("izquierda"):
            grosor = 3 if danos.get("izquierda", 0) < 2 else 1
            estilo = '-' if danos.get("izquierda", 0) < 2 else ':'
            ax.plot([x, x], [y, y+1], "k"+estilo, linewidth=grosor)
        if paredes.get("derecha"):
            grosor = 3 if danos.get("derecha", 0) < 2 else 1
            estilo = '-' if danos.get("derecha", 0) < 2 else ':'
            ax.plot([x+1, x+1], [y, y+1], "k"+estilo, linewidth=grosor)

    # PUERTAS
    for (celda1, celda2), puerta_info in model.puertas.items():
        x1, y1 = celda1
        x2, y2 = celda2

        color = "green" if puerta_info["abierta"] else "brown"
        estilo = "--" if puerta_info["abierta"] else "-"
        grosor = 4 if puerta_info["abierta"] else 5

        if x1 == x2:  # horizontal
            y_p = (y1 + y2) / 2 + 0.5
            ax.plot([x1, x1+1], [y_p, y_p], color=color, linestyle=estilo, linewidth=grosor)
        else:         # vertical
            x_p = (x1 + x2) / 2 + 0.5
            ax.plot([x_p, x_p], [y1, y1+1], color=color, linestyle=estilo, linewidth=grosor)

    ax.set_xlim(0, model.grid.width)
    ax.set_ylim(0, model.grid.height)
    ax.set_aspect("equal")
    ax.invert_yaxis()
    ax.set_title(f"Flash Point - Step {step_num}")

    if ax is None:
        plt.tight_layout()
        plt.show()

import copy
import pandas as pd
import matplotlib.pyplot as plt

def ejecutar_simulacion_con_animacion(tipo_agente, max_steps=100, archivo_config='config.txt'):
    """
    Ejecuta simulación guardando UN frame por step (más eficiente)
    """
    model = Tablero(width=8, height=6, num_agentes=6,
                   tipo_agente=tipo_agente, archivo_config=archivo_config)

    history_models = []
    history_models.append(copy.deepcopy(model))

    print(f"Iniciando simulación...")
    print(f"Agentes: {len(model.schedule)}")
    print(f"Civiles iniciales: {np.sum(model.cells == 3)}")
    print(f"Fuegos iniciales: {len(model.posicionesFuego)}")

    for step in range(max_steps):
        if step % 10 == 0:
            print(f"  Step {step}...")

        model.step()
        # Guardar solo UN frame por step (en lugar de uno por acción)
        history_models.append(copy.deepcopy(model))

        # Verificar condiciones de término
        game_over, razon = model.verificar_game_over()
        if game_over:
            print(f"¡DERROTA! Razón: {razon} en step {step}")
            break

        if model.is_all_collected():
            print(f"¡VICTORIA! 7 civiles rescatados en step {step}!")
            break

    print(f"\nSimulación completada:")
    print(f"  Total frames: {len(history_models)}")
    print(f"  Steps ejecutados: {model.steps}")
    print(f"  Civiles rescatados: {model.civiles_rescatados}")
    print(f"  Civiles perdidos: {model.civiles_perdidos}")
    print(f"  POI restantes: {len(model.posicionesPOI)}")
    print(f"  Fuegos apagados: {sum(a.apagarFuego for a in model.schedule)}")
    print(f"  Humos apagados: {sum(a.apagarHumo for a in model.schedule)}")
    print(f"  Puntos de daño: {model.puntos_dano}")

    game_over, razon = model.verificar_game_over()
    if game_over:
        print(f"  Resultado: DERROTA ({razon})")
    elif model.is_all_collected():
        print(f"  Resultado: VICTORIA")
    else:
        print(f"  Resultado: Simulación incompleta")

    return history_models


def ejecutar_simulacion_detallada(tipo_agente, max_steps=30, archivo_config='config.txt',
                                   frames_por_agente=False):
    """
    Ejecuta simulación con control de frames
    Si frames_por_agente=True, guarda frame por movimiento (muchos frames)
    Si frames_por_agente=False, guarda frame por step (menos frames)
    """
    model = Tablero(width=8, height=6, num_agentes=6,
                   tipo_agente=tipo_agente, archivo_config=archivo_config)

    history_models = []
    history_models.append(copy.deepcopy(model))

    print(f"Ejecutando simulación detallada...")
    print(f"Agentes: {len(model.schedule)}")
    print(f"Civiles iniciales: {np.sum(model.cells == 3)}")

    for step in range(max_steps):
        if step % 5 == 0:
            print(f"  Step {step}...")

        if frames_por_agente:
            # Guardar frame por cada agente
            for agent in model.schedule:
                agent.step()
                model.generar_fuego()
                history_models.append(copy.deepcopy(model))
            model.steps += 1
            model.datacollector.collect(model)
        else:
            # Guardar solo un frame por step completo
            model.step()
            history_models.append(copy.deepcopy(model))

        # Verificar condiciones de término
        game_over, razon = model.verificar_game_over()
        if game_over or model.is_all_collected():
            print(f"  Terminó en step {step}")
            break

    print(f"\nSimulación completada:")
    print(f"  Frames totales: {len(history_models)}")
    print(f"  Steps ejecutados: {model.steps}")
    print(f"  Civiles rescatados: {model.civiles_rescatados}")
    print(f"  Civiles perdidos: {model.civiles_perdidos}")
    print(f"  Fuegos apagados: {sum(a.apagarFuego for a in model.schedule)}")

    return history_models


def comparar_estrategias(archivo_config='config.txt', num_simulaciones=10):
    """
    Compara estrategias aleatoria vs inteligente
    """
    resultados_aleatorio = []
    resultados_inteligente = []

    print("\nComparando estrategias con", num_simulaciones, "simulaciones...")

    for i in range(num_simulaciones):
        print(f"  Simulación {i+1}/{num_simulaciones}")

        try:
            # Estrategia aleatoria
            model_random = Tablero(width=8, height=6, num_agentes=6,
                                  tipo_agente=BomberoAleatorio,
                                  archivo_config=archivo_config)

            for step in range(100):
                model_random.step()
                game_over, _ = model_random.verificar_game_over()
                if model_random.is_all_collected() or game_over:
                    break

            resultados_aleatorio.append({
                'civiles_rescatados': model_random.civiles_rescatados,
                'civiles_perdidos': model_random.civiles_perdidos,
                'victoria': model_random.is_all_collected(),
                'steps': model_random.steps,
                'puertas_abiertas': sum(1 for p in model_random.puertas.values() if p['abierta']),
                'puntos_dano': model_random.puntos_dano,
                'fuegos_apagados': sum(a.apagarFuego for a in model_random.schedule),
                'humos_apagados': sum(a.apagarHumo for a in model_random.schedule)
            })

        except Exception as e:
            print(f"    Error en simulación aleatoria {i+1}: {e}")
            resultados_aleatorio.append({
                'civiles_rescatados': 0, 'civiles_perdidos': 4, 'victoria': False,
                'steps': 100, 'puertas_abiertas': 0,
                'puntos_dano': 25, 'fuegos_apagados': 0, 'humos_apagados': 0
            })

        try:
            # Estrategia inteligente
            model_smart = Tablero(width=8, height=6, num_agentes=6,
                                tipo_agente=Bombero,
                                archivo_config=archivo_config)

            for step in range(100):
                model_smart.step()
                game_over, _ = model_smart.verificar_game_over()
                if model_smart.is_all_collected() or game_over:
                    break

            resultados_inteligente.append({
                'civiles_rescatados': model_smart.civiles_rescatados,
                'civiles_perdidos': model_smart.civiles_perdidos,
                'victoria': model_smart.is_all_collected(),
                'steps': model_smart.steps,
                'puertas_abiertas': sum(1 for p in model_smart.puertas.values() if p['abierta']),
                'puntos_dano': model_smart.puntos_dano,
                'fuegos_apagados': sum(a.apagarFuego for a in model_smart.schedule),
                'humos_apagados': sum(a.apagarHumo for a in model_smart.schedule)
            })

        except Exception as e:
            print(f"    Error en simulación inteligente {i+1}: {e}")
            resultados_inteligente.append({
                'civiles_rescatados': 0, 'civiles_perdidos': 4, 'victoria': False,
                'steps': 100, 'puertas_abiertas': 0,
                'puntos_dano': 25, 'fuegos_apagados': 0, 'humos_apagados': 0
            })

    # Crear DataFrames
    df_aleatorio = pd.DataFrame(resultados_aleatorio)
    df_inteligente = pd.DataFrame(resultados_inteligente)

    if df_aleatorio.empty or df_inteligente.empty:
        print("Error: DataFrames vacíos")
        return df_aleatorio, df_inteligente

    # Mostrar estadísticas
    print("\n=== RESULTADOS COMPARATIVOS ===")
    print("\nEstrategia Aleatoria:")
    print(df_aleatorio.describe())
    print("\nEstrategia Inteligente:")
    print(df_inteligente.describe())

    # Gráficas comparativas (3x3 grid)
    fig, axes = plt.subplots(3, 3, figsize=(18, 15))

    # Fila 1
    # Civiles rescatados
    axes[0, 0].boxplot([df_aleatorio['civiles_rescatados'].values,
                     df_inteligente['civiles_rescatados'].values],
                    labels=['Aleatorio', 'Inteligente'])
    axes[0, 0].set_title('Civiles Rescatados')
    axes[0, 0].set_ylabel('Cantidad')
    axes[0, 0].grid(True, alpha=0.3)

    # Civiles perdidos
    axes[0, 1].boxplot([df_aleatorio['civiles_perdidos'].values,
                     df_inteligente['civiles_perdidos'].values],
                    labels=['Aleatorio', 'Inteligente'])
    axes[0, 1].set_title('Civiles Perdidos')
    axes[0, 1].set_ylabel('Cantidad')
    axes[0, 1].grid(True, alpha=0.3)

    # Victorias
    victorias_aleatorio = df_aleatorio['victoria'].sum()
    victorias_inteligente = df_inteligente['victoria'].sum()
    axes[0, 2].bar(['Aleatorio', 'Inteligente'],
                   [victorias_aleatorio, victorias_inteligente])
    axes[0, 2].set_title('Victorias')
    axes[0, 2].set_ylabel('Cantidad')
    axes[0, 2].grid(True, alpha=0.3, axis='y')

    # Fila 2
    # Pasos necesarios
    axes[1, 0].boxplot([df_aleatorio['steps'].values,
                     df_inteligente['steps'].values],
                    labels=['Aleatorio', 'Inteligente'])
    axes[1, 0].set_title('Pasos Necesarios')
    axes[1, 0].set_ylabel('Steps')
    axes[1, 0].grid(True, alpha=0.3)

    # Puntos de daño
    axes[1, 1].boxplot([df_aleatorio['puntos_dano'].values,
                     df_inteligente['puntos_dano'].values],
                    labels=['Aleatorio', 'Inteligente'])
    axes[1, 1].set_title('Puntos de Daño')
    axes[1, 1].set_ylabel('Daño')
    axes[1, 1].grid(True, alpha=0.3)

    # Puertas abiertas
    axes[1, 2].boxplot([df_aleatorio['puertas_abiertas'].values,
                     df_inteligente['puertas_abiertas'].values],
                    labels=['Aleatorio', 'Inteligente'])
    axes[1, 2].set_title('Puertas Abiertas')
    axes[1, 2].set_ylabel('Cantidad')
    axes[1, 2].grid(True, alpha=0.3)

    # Fila 3
    # Fuegos apagados
    axes[2, 0].boxplot([df_aleatorio['fuegos_apagados'].values,
                     df_inteligente['fuegos_apagados'].values],
                    labels=['Aleatorio', 'Inteligente'])
    axes[2, 0].set_title('Fuegos Apagados')
    axes[2, 0].set_ylabel('Cantidad')
    axes[2, 0].grid(True, alpha=0.3)

    # Humos apagados
    axes[2, 1].boxplot([df_aleatorio['humos_apagados'].values,
                     df_inteligente['humos_apagados'].values],
                    labels=['Aleatorio', 'Inteligente'])
    axes[2, 1].set_title('Humos Apagados')
    axes[2, 1].set_ylabel('Cantidad')
    axes[2, 1].grid(True, alpha=0.3)

    # Espacio vacío o métrica adicional
    axes[2, 2].axis('off')

    plt.suptitle('Comparación de Estrategias', fontsize=16, fontweight='bold')
    plt.tight_layout()
    plt.show()

    # Calcular mejoras
    mejora_civiles = ((df_inteligente['civiles_rescatados'].mean() -
                      df_aleatorio['civiles_rescatados'].mean()) /
                     max(df_aleatorio['civiles_rescatados'].mean(), 0.001) * 100)

    mejora_fuegos = ((df_inteligente['fuegos_apagados'].mean() -
                     df_aleatorio['fuegos_apagados'].mean()) /
                    max(df_aleatorio['fuegos_apagados'].mean(), 0.001) * 100)

    print(f"\n=== MEJORA DE LA ESTRATEGIA INTELIGENTE ===")
    print(f"Victorias (Aleatorio): {victorias_aleatorio}/{num_simulaciones}")
    print(f"Victorias (Inteligente): {victorias_inteligente}/{num_simulaciones}")
    print(f"Civiles rescatados (Aleatorio): {df_aleatorio['civiles_rescatados'].mean():.2f}")
    print(f"Civiles rescatados (Inteligente): {df_inteligente['civiles_rescatados'].mean():.2f}")
    print(f"Mejora en rescates: {mejora_civiles:.1f}%")
    print(f"\nCiviles perdidos (Aleatorio): {df_aleatorio['civiles_perdidos'].mean():.2f}")
    print(f"Civiles perdidos (Inteligente): {df_inteligente['civiles_perdidos'].mean():.2f}")
    print(f"\nFuegos apagados (Aleatorio): {df_aleatorio['fuegos_apagados'].mean():.2f}")
    print(f"Fuegos apagados (Inteligente): {df_inteligente['fuegos_apagados'].mean():.2f}")
    print(f"Mejora en combate: {mejora_fuegos:.1f}%")

    return df_aleatorio, df_inteligente

import matplotlib.animation as animation
import matplotlib.patches as patches
from matplotlib.lines import Line2D

def animar_simulacion(history_models, interval=200):
    """
    Crea animación básica de la simulación
    """
    fig, ax = plt.subplots(figsize=(12, 8))

    def update(frame):
        ax.clear()
        model = history_models[frame]

        # Dibujar celdas
        for x in range(model.grid.width):
            for y in range(model.grid.height):
                color = 'white'

                # BASE
                if (x, y) in model.base_position: # Changed to 'in'
                    color = 'yellow'
                # FUEGO
                elif (x, y) in model.posicionesFuego:
                    color = 'orange'
                # HUMO
                elif (x, y) in model.posicionesHumo:
                    color = 'gray'
                # CIVIL
                elif model.cells[x][y] == 3:
                    color = 'lightblue'

                rect = patches.Rectangle((x, y), 1, 1,
                                        linewidth=0.5,
                                        edgecolor='gray',
                                        facecolor=color,
                                        alpha=0.7)
                ax.add_patch(rect)

                # Texto civil
                if model.cells[x][y] == 3:
                    ax.text(x+0.5, y+0.5, 'C',
                           ha='center', va='center',
                           fontsize=12, fontweight='bold')

                # Texto base
                if (x, y) in model.base_position: # Changed to 'in'
                    ax.text(x+0.5, y+0.5, 'BASE',
                           ha='center', va='center',
                           fontsize=10, fontweight='bold')

        # Dibujar bomberos
        for i, agent in enumerate(model.schedule):
            x, y = agent.pos
            circle = patches.Circle((x+0.5, y+0.5), 0.3,
                                   color='red', alpha=0.8)
            ax.add_patch(circle)

            texto = f"B{i+1}"
            if agent.tieneCivil:
                texto += "+C"

            ax.text(x+0.5, y+0.5, texto,
                   ha='center', va='center',
                   fontsize=8 if agent.tieneCivil else 10,
                   color='white', fontweight='bold')

        # Dibujar paredes
        for (x, y), paredes in model.paredes.items():
            if paredes.get('arriba', False):
                ax.plot([x, x+1], [y, y], 'k-', linewidth=3)
            if paredes.get('abajo', False):
                ax.plot([x, x+1], [y+1, y+1], 'k-', linewidth=3)
            if paredes.get('izquierda', False):
                ax.plot([x, x], [y, y+1], 'k-', linewidth=3)
            if paredes.get('derecha', False):
                ax.plot([x+1, x+1], [y, y+1], 'k-', linewidth=3)

        # Dibujar puertas
        for (celda1, celda2), puerta_info in model.puertas.items():
            x1, y1 = celda1
            x2, y2 = celda2

            if puerta_info['abierta']:
                color = 'green'
                estilo = '--'
                grosor = 4
            else:
                color = 'brown'
                estilo = '-'
                grosor = 5

            if x1 == x2:
                y_puerta = (y1 + y2) / 2 + 0.5
                ax.plot([x1, x1+1], [y_puerta, y_puerta],
                       color=color, linestyle=estilo, linewidth=grosor)
            else:
                x_puerta = (x1 + x2) / 2 + 0.5
                ax.plot([x_puerta, x_puerta], [y1, y1+1],
                       color=color, linestyle=estilo, linewidth=grosor)

        # Configuración
        ax.set_xlim(0, model.grid.width)
        ax.set_ylim(0, model.grid.height)
        ax.set_aspect('equal')
        ax.invert_yaxis()
        ax.set_xticks(range(model.grid.width + 1))
        ax.set_yticks(range(model.grid.height + 1))
        ax.grid(True, alpha=0.2, linestyle=':')

        ax.set_title(f'Flash Point: Fire Rescue - Frame {frame}/{len(history_models)-1}',
                    fontsize=14, fontweight='bold')

        return []

    anim = animation.FuncAnimation(
        fig, update,
        frames=len(history_models),
        interval=interval,
        repeat=True
    )

    plt.tight_layout()
    return anim


def animar_simulacion_detallada(history_models, interval=100):
    """
    Crea animación con información adicional
    """
    fig, ax = plt.subplots(figsize=(14, 9))

    def update(frame):
        ax.clear()
        model = history_models[frame]

        # Dibujar celdas
        for x in range(model.grid.width):
            for y in range(model.grid.height):
                color = 'white'

                if (x, y) in model.base_position: # Changed to 'in'
                    color = 'yellow'
                elif (x, y) in model.posicionesFuego:
                    color = 'orange'
                elif (x, y) in model.posicionesHumo:
                    color = 'gray'
                elif model.cells[x][y] == 3:
                    color = 'lightblue'

                rect = patches.Rectangle((x, y), 1, 1,
                                        linewidth=0.5,
                                        edgecolor='gray',
                                        facecolor=color,
                                        alpha=0.7)
                ax.add_patch(rect)

                if model.cells[x][y] == 3:
                    ax.text(x+0.5, y+0.5, 'C',
                           ha='center', va='center',
                           fontsize=12, fontweight='bold')

                if (x, y) in model.base_position: # Changed to 'in'
                    ax.text(x+0.5, y+0.5, 'BASE',
                           ha='center', va='center',
                           fontsize=10, fontweight='bold')

        # Dibujar bomberos
        for i, agent in enumerate(model.schedule):
            x, y = agent.pos
            circle = patches.Circle((x+0.5, y+0.5), 0.3,
                                   color='red', alpha=0.8)
            ax.add_patch(circle)

            texto = f"B{i+1}"
            if agent.tieneCivil:
                texto += "+C"

            ax.text(x+0.5, y+0.5, texto,
                   ha='center', va='center',
                   fontsize=8 if agent.tieneCivil else 10,
                   color='white', fontweight='bold')

        # Dibujar paredes
        for (x, y), paredes in model.paredes.items():
            if paredes.get('arriba', False):
                ax.plot([x, x+1], [y, y], 'k-', linewidth=3)
            if paredes.get('abajo', False):
                ax.plot([x, x+1], [y+1, y+1], 'k-', linewidth=3)
            if paredes.get('izquierda', False):
                ax.plot([x, x], [y, y+1], 'k-', linewidth=3)
            if paredes.get('derecha', False):
                ax.plot([x+1, x+1], [y, y+1], 'k-', linewidth=3)

        # Dibujar puertas
        for (celda1, celda2), puerta_info in model.puertas.items():
            x1, y1 = celda1
            x2, y2 = celda2

            if puerta_info['abierta']:
                color = 'green'
                estilo = '--'
                grosor = 4
            else:
                color = 'brown'
                estilo = '-'
                grosor = 5

            if x1 == x2:
                y_puerta = (y1 + y2) / 2 + 0.5
                ax.plot([x1, x1+1], [y_puerta, y_puerta],
                       color=color, linestyle=estilo, linewidth=grosor)
            else:
                x_puerta = (x1 + x2) / 2 + 0.5
                ax.plot([x_puerta, x_puerta], [y1, y1+1],
                       color=color, linestyle=estilo, linewidth=grosor)

        # Configuración
        ax.set_xlim(0, model.grid.width)
        ax.set_ylim(0, model.grid.height)
        ax.set_aspect('equal')
        ax.invert_yaxis()
        ax.set_xticks(range(model.grid.width + 1))
        ax.set_yticks(range(model.grid.height + 1))
        ax.grid(True, alpha=0.2, linestyle=':')

        ax.set_title(f'Flash Point: Fire Rescue - Frame {frame}/{len(history_models)-1}',
                    fontsize=14, fontweight='bold')

        # Información adicional
        civiles_rescatados = model.civiles_rescatados # Now reflects actual rescued count
        # Note: model.cells == 3 is deprecated for civil tracking. Use model.civiles_revelados.
        # To accurately display remaining civilians, you'd need to count from civiles_revelados
        civiles_restantes = len(model.civiles_revelados) # Count unrescued civilians
        puertas_abiertas = sum(1 for p in model.puertas.values() if p['abierta'])

        info_text = ax.text(8.5, 3,
                           f'Step: {model.steps}\n'
                           f'Civiles rescatados: {civiles_rescatados}\n'
                           f'Civiles restantes: {civiles_restantes}\n'
                           f'Puertas abiertas: {puertas_abiertas}\n'
                           f'Fuegos activos: {len(model.posicionesFuego)}\n'
                           f'Puntos de daño: {model.puntos_dano}',
                           fontsize=10,
                           bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.8))

        # Leyenda
        legend_elements = [
            Line2D([0], [0], marker='o', color='w', markerfacecolor='red',
                   markersize=10, label='Bombero'),
            Line2D([0], [0], marker='s', color='w', markerfacecolor='lightblue',
                   markersize=10, label='Civil'),
            Line2D([0], [0], marker='s', color='w', markerfacecolor='yellow',
                   markersize=10, label='Base'),
            Line2D([0], [0], marker='s', color='w', markerfacecolor='orange',
                   markersize=10, label='Fuego'),
            Line2D([0], [0], marker='s', color='w', markerfacecolor='gray',
                   markersize=10, label='Humo'),
            Line2D([0], [0], color='black', linewidth=3, label='Pared'),
            Line2D([0], [0], color='brown', linewidth=4, label='Puerta Cerrada'),
            Line2D([0], [0], color='green', linewidth=4, linestyle='--',
                   label='Puerta Abierta')
        ]
        ax.legend(handles=legend_elements, loc='upper left',
                 bbox_to_anchor=(1.05, 1), fontsize=9)

        return []

    anim = animation.FuncAnimation(
        fig, update,
        frames=len(history_models),
        interval=interval,
        repeat=True
    )

    plt.tight_layout()
    return anim

# ==========================================
# CREAR ARCHIVO DE CONFIGURACIÓN
# ==========================================
config_text = """1001 1000 1100 1001 1100 1001 1000 1100
0001 0000 0110 0011 0110 0011 0010 0110
0001 0100 1001 1000 1000 1100 1001 1100
0011 0110 0011 0010 0010 0110 0011 0110
1001 1000 1000 1000 1100 1001 1100 1101
0011 0010 0010 0010 0110 0011 0110 0111
2 4 v
5 1 f
5 8 v
2 2
2 3
3 2
3 3
3 4
3 5
4 4
5 6
5 7
6 6
1 3 1 4
2 5 2 6
2 8 3 8
3 2 3 3
4 4 5 4
4 6 4 7
6 5 6 6
6 7 6 8
1 6
3 1
4 8
6 3"""

with open('config.txt', 'w') as f:
    f.write(config_text)

print("✅ Archivo de configuración creado")

# ==========================================
# 1. EJECUTAR SIMULACIONES BÁSICAS
# ==========================================
print("\n" + "="*50)
print("FLASH POINT: FIRE RESCUE")
print("="*50)

# Ejecutar simulación inteligente
print("\n📊 Ejecutando estrategia INTELIGENTE...")
history_smart = ejecutar_simulacion_con_animacion(
    tipo_agente=Bombero,
    max_steps=100,
    archivo_config='config.txt'
)

# Ejecutar simulación aleatoria
print("\n🎲 Ejecutando estrategia ALEATORIA...")
history_random = ejecutar_simulacion_con_animacion(
    tipo_agente=BomberoAleatorio,
    max_steps=100,
    archivo_config='config.txt'
)

# ==========================================
# 2. COMPARAR ESTRATEGIAS (10 SIMULACIONES)
# ==========================================
print("\n" + "="*50)
print("COMPARACIÓN DE ESTRATEGIAS")
print("="*50)

df_aleatorio, df_inteligente = comparar_estrategias(
    archivo_config='config.txt',
    num_simulaciones=10
)

# ==========================================
# 3. SIMULACIÓN DETALLADA (OPTIMIZADA - menos frames)
# ==========================================
print("\n" + "="*50)
print("SIMULACIÓN DETALLADA")
print("="*50)

print("\n📊 Estrategia Inteligente (detallada):")
history_detallado_smart = ejecutar_simulacion_detallada(
    tipo_agente=Bombero,
    max_steps=50,  # Aumentamos steps
    archivo_config='config.txt',
    frames_por_agente=False  # ⚠️ IMPORTANTE: False = menos frames
)

# ==========================================
# 4. CREAR ANIMACIONES (más rápidas)
# ==========================================
print("\n" + "="*50)
print("CREANDO ANIMACIONES")
print("="*50)

# Animación básica (un frame por step)
print("\n🎬 Creando animación básica (estrategia inteligente)...")
anim_smart = animar_simulacion(history_smart, interval=300)  # 300ms por frame

# ==========================================
# 5. MOSTRAR ANIMACIÓN EN JUPYTER
# ==========================================
from IPython.display import HTML

print("\n✅ Todo listo! Mostrando animación...")
print(f"Total de frames: {len(history_smart)}")

# Muestra la animación básica (menos pesada)
HTML(anim_smart.to_jshtml())

# ==========================================
# OPCIONAL: GUARDAR COMO GIF
# ==========================================
# Descomenta las siguientes líneas si quieres guardar como GIF:
# print("\n💾 Guardando animación como GIF...")
# anim_detallado.save('simulacion_detallada.gif', writer='pillow', fps=10)
# print("✅ GIF guardado como 'simulacion_detallada.gif'")

import copy
import numpy as np

def ejecutar_simulacion_accion_por_accion(tipo_agente, max_steps=50, archivo_config='config.txt',
                                          max_frames=5000, verbose=True):
    """
    Ejecuta simulación guardando UN frame por cada ACCIÓN de agente.
    - Reproduce la lógica de acción que usan tus agentes (movimiento/puerta/nada).
    - Genera fuego justo después de cada acción (regla estricta).
    - max_frames: límite protector para evitar memory blowup.
    """
    model = Tablero(width=8, height=6, num_agentes=6,
                   tipo_agente=tipo_agente, archivo_config=archivo_config)

    history_models = []
    history_models.append(copy.deepcopy(model))

    frames = 1
    if verbose:
        print("Iniciando simulación acción-por-acción...")
        print(f"Agentes: {len(model.schedule)} - Civiles: {np.sum(model.cells==3)} - Fuegos: {len(model.posicionesFuego)}")

    for step in range(max_steps):
        if verbose and (step % 5 == 0):
            print(f" Step {step} ... frames guardados: {frames}")

        # Recorremos cada agente y ejecutamos sus acciones una a una
        for agent_idx, agent in enumerate(list(model.schedule)):
            # Preparar al agente (igual que en tu detallada)
            # recargar energía inicial del turno
            agent.energia_actual = agent.energia_maxima + agent.energia_guardada
            agent.energia_guardada = 0

            # Si tiene civil y está en base, entregar inmediatamente (y guardar estado)
            if hasattr(agent, "tieneCivil") and agent.tieneCivil and agent.pos == model.base_position:
                agent.tieneCivil = False
                history_models.append(copy.deepcopy(model))
                frames += 1
                if frames >= max_frames:
                    if verbose: print("Máximo de frames alcanzado, abortando.")
                    return history_models

            # Ejecutar acciones una por una hasta que se agote energía
            while getattr(agent, "energia_actual", 0) > 0:
                # Guardar estado anterior para detectar cambios (opcional)
                pos_antes = getattr(agent, "pos", None)
                energia_antes = getattr(agent, "energia_actual", None)
                civil_antes = getattr(agent, "tieneCivil", None)

                # --- lógica para bombero aleatorio vs inteligente ---
                if isinstance(agent, BomberoAleatorio):
                    accion = np.random.choice(['mover', 'puerta', 'nada'], p=[0.7, 0.2, 0.1])

                    if accion == 'mover':
                        agent.movimiento_aleatorio()
                    elif accion == 'puerta':
                        vecinos = list(agent.get_neighbors())
                        if vecinos:
                            idx = np.random.choice(len(vecinos))
                            vecino = vecinos[idx]
                            if model.hay_puerta_entre(agent.pos, vecino):
                                agent.abrir_puerta(agent.pos, vecino)
                            else:
                                agent.gastar_energia()
                        else:
                            agent.gastar_energia()
                    else:
                        agent.gastar_energia()

                else:
                    # Bombero "inteligente" (usa tus métodos existentes)
                    accion_realizada = False

                    if getattr(agent, "tieneCivil", False):
                        if agent.pos != model.base_position:
                            accion_realizada = agent.mover_hacia(model.base_position)
                        else:
                            accion_realizada = agent.gastar_energia()
                    else:
                        civil_objetivo = agent.encontrar_civil_mas_cercano()
                        if civil_objetivo:
                            accion_realizada = agent.mover_hacia(civil_objetivo)
                        else:
                            accion_realizada = agent.movimiento_aleatorio()

                    if not accion_realizada:
                        agent.gastar_energia()

                # --- Después de CADA acción: generar fuego (regla) y guardar frame ---
                model.generar_fuego()

                history_models.append(copy.deepcopy(model))
                frames += 1

                # Límite de seguridad en frames
                if frames >= max_frames:
                    if verbose: print("Máximo de frames alcanzado, abortando.")
                    return history_models

                # Si se rescata un civil y llega a base, se habrá registrado en state
                # Nota: no incrementamos model.steps aquí; se hace después de ciclo completo

        # Fin de turno (todos los agentes actuaron una vez)
        model.steps += 1
        model.datacollector.collect(model)

        # Comprobaciones de fin
        game_over, razon = (False, None)
        if hasattr(model, "verificar_game_over"):
            game_over, razon = model.verificar_game_over()
        if game_over:
            if verbose: print(f"Game over en step {step}: {razon}")
            break
        if model.is_all_collected():
            if verbose: print(f"Todos los civiles rescatados en step {step}")
            break

    if verbose:
        print("Simulación acción-por-acción completada.")
        print(f"Frames guardados: {len(history_models)} - Steps ejecutados: {model.steps}")

    return history_models


def ejecutar_simulacion_detallada_accion_por_accion(tipo_agente, max_steps=30, archivo_config='config.txt',
                                                    frames_por_agente=True, max_frames=5000, verbose=True):
    """
    Variante de la detallada que guarda frame por acción (frames_por_agente=True)
    Si frames_por_agente=False guarda un frame por step (más compacto).
    """
    if not frames_por_agente:
        # Reusar la versión paso-a-paso simple (un frame por step)
        return ejecutar_simulacion_accion_por_accion(tipo_agente, max_steps=max_steps,
                                                     archivo_config=archivo_config,
                                                     max_frames=max_frames, verbose=verbose)

    model = Tablero(width=8, height=6, num_agentes=6,
                   tipo_agente=tipo_agente, archivo_config=archivo_config)

    history_models = [copy.deepcopy(model)]
    frames = 1

    if verbose:
        print("Ejecutando simulación detallada acción-por-acción...")
        print(f"Agentes: {len(model.schedule)} - Civiles: {np.sum(model.cells==3)} - Fuegos: {len(model.posicionesFuego)}")

    for step in range(max_steps):
        if verbose and (step % 5 == 0):
            print(f" Step {step} ... frames: {frames}")

        # Para cada agente: recargar energía y ejecutar acciones una a una
        for agent in list(model.schedule):
            agent.energia_actual = agent.energia_maxima + agent.energia_guardada
            agent.energia_guardada = 0

            # entrega de civil si aplica
            if getattr(agent, "tieneCivil", False) and agent.pos == model.base_position:
                agent.tieneCivil = False
                history_models.append(copy.deepcopy(model))
                frames += 1
                if frames >= max_frames:
                    if verbose: print("Máximo de frames alcanzado")
                    return history_models

            while getattr(agent, "energia_actual", 0) > 0:
                # Ejecutar EXACTAMENTE UNA acción (mismo bloque que arriba)
                if isinstance(agent, BomberoAleatorio):
                    accion = np.random.choice(['mover', 'puerta', 'nada'], p=[0.7,0.2,0.1])
                    if accion == 'mover':
                        agent.movimiento_aleatorio()
                    elif accion == 'puerta':
                        vecinos = list(agent.get_neighbors())
                        if vecinos:
                            vecino = vecinos[np.random.randint(len(vecinos))]
                            if model.hay_puerta_entre(agent.pos, vecino):
                                agent.abrir_puerta(agent.pos, vecino)
                            else:
                                agent.gastar_energia()
                        else:
                            agent.gastar_energia()
                    else:
                        agent.gastar_energia()
                else:
                    accion_realizada = False
                    if getattr(agent, "tieneCivil", False):
                        if agent.pos != model.base_position:
                            accion_realizada = agent.mover_hacia(model.base_position)
                        else:
                            accion_realizada = agent.gastar_energia()
                    else:
                        civil_objetivo = agent.encontrar_civil_mas_cercano()
                        if civil_objetivo:
                            accion_realizada = agent.mover_hacia(civil_objetivo)
                        else:
                            accion_realizada = agent.movimiento_aleatorio()

                    if not accion_realizada:
                        agent.gastar_energia()

                # Regla: generar fuego después de cada acción
                model.generar_fuego()

                history_models.append(copy.deepcopy(model))
                frames += 1
                if frames >= max_frames:
                    if verbose: print("Máximo de frames alcanzado")
                    return history_models

            # Guardar energía sobrante para el siguiente turno del agente
            if getattr(agent, "energia_actual", 0) > 0:
                agent.energia_guardada = min(agent.energia_actual, agent.energia_maxima)

        # Fin de turno completo
        model.steps += 1
        model.datacollector.collect(model)

        # Comprobación final
        if hasattr(model, "verificar_game_over"):
            game_over, razon = model.verificar_game_over()
            if game_over:
                if verbose: print(f"Game over: {razon}")
                break
        if model.is_all_collected():
            if verbose: print("Todos los civiles rescatados")
            break

    if verbose:
        print("Detalle acción-por-acción completado.")
        print(f"Frames guardados: {len(history_models)} Steps: {model.steps}")

    return history_models

import matplotlib.pyplot as plt
import numpy as np

def visualizar_history(history_models):
    """
    Visualiza cada frame de la simulación (acción por acción).
    Usa model.cells como matriz de 0–6.
    """
    for i, model in enumerate(history_models):
        grid = np.array(model.cells)

        plt.figure(figsize=(6, 5))
        plt.imshow(grid, cmap="tab20", vmin=0, vmax=8)
        plt.title(f"Frame {i} - Step {model.steps}")
        plt.colorbar()
        plt.show()

history = ejecutar_simulacion_accion_por_accion(
    tipo_agente=Bombero,
    max_steps=20,
    archivo_config="config.txt"
)

visualizar_history(history)

"""# Task
Correct the civil rescue logic in the Flash Point simulation. Ensure that `civiles_rescatados` is incremented only when a `Bombero` agent carrying a civilian (`tieneCivil = True`) successfully delivers them to the `base_position`. Update the `Bombero` agent's `step` method to include this delivery action and set `tieneCivil` to `False` afterward. Verify that the `is_all_collected` function in the `Tablero` class accurately reflects this updated rescue condition and that the victory condition (7 rescued civilians) is met correctly. Finally, re-run and compare simulations with both intelligent and random strategies to confirm the proper functioning of the rescue logic and victory/defeat conditions.

## Actualizar Lógica de Rescate de Civil

### Subtask:
Modificar el método `quitar_civil` en la clase `Tablero` y el `step` del agente `Bombero` para que el contador `civiles_rescatados` se incremente únicamente cuando un bombero con un civil (`tieneCivil = True`) llega a la posición `base_position` del modelo y entrega al civil. La variable `tieneCivil` del agente se establecerá en `False` después de la entrega.

**Reasoning**:
The subtask requires modifying the `Tablero` class to remove `self.civiles_rescatados += 1` from the `quitar_civil` method, as the increment of `civiles_rescatados` should only occur when a firefighter delivers a civilian to the base.
"""